### ISSUE TITLE
Merging secrets does not work as expected

### ISSUE THREAD

**Issue by mazzy89** [fluxcd/helm-operator#126]
**Describe the bug**

I have the following YAML in an Helm chart `values.yaml`

```yaml
      config:
        global:
          resolve_timeout: 5m

        receivers:
          - name: "opsgenie_team1"
            opsgenie_configs:
              - responders:
                  - name: team1
                    type: team
                message: '{{`{{ template "opsgenie.message" . }}`}}'
                description: '{{`{{ template "opsgenie.description" . }}`}}'
          - name: "opsgenie_team2"
            opsgenie_configs:
              - responders:
                  - name: team2
                    type: team
                message: '{{`{{ template "opsgenie.message" . }}`}}'
                description: '{{`{{ template "opsgenie.description" . }}`}}'
```

and I fetch secrets in this way:

```yaml
   valuesFrom:
    - secretKeyRef:
        # Name of the secret, must be in the same namespace as the
        # HelmRelease
        name: alertmanager # mandatory
        # Key in the secret to get thre values from
        key: values.yaml # optional; defaults to values.yaml
        # If set to true successful retrieval of the values file is no
        # longer mandatory
        optional: false # optional; defaults to false
```

The Secret `values.yaml` files that is supposed to merged looks like:

```
values.yaml:
      config:
        receivers:
          - name: "opsgenie_team1"
            opsgenie_configs:
              - api_key: ""
          - name: "opsgenie_team2"
            opsgenie_configs:
              - api_key: ""
```

but the merging does not work as expected. I believe that it is not possible to merge at that level. am I right?

**To Reproduce**
Steps to reproduce the behaviour:
0. What's your setup?

**Expected behavior**

**Logs**
If applicable, please provide logs. In a standard stand-alone installation, you'd get this by running `kubectl logs -n default deploy/flux-helm-operator`.

**Additional context**
Add any other context about the problem here, e.g 
- Helm operator version: 
- Kubernetes version: 1.15.6
- Git provider:
- Container registry provider:
