### ISSUE TITLE
Get Helm repository credentials from k8s secret

### ISSUE THREAD

**Issue by Francois-Royer** [fluxcd/helm-operator#140]
We are using a private helm registry. The only way to provide credential it to use https://user:password@repohost/ plaintext syntax which cause security issue. You should add possibility to get credentials from a k8s secret.

**Comment by Francois-Royer** [comment]
We are using a private helm registry. The only way to provide credential it to use https://user:password@repohost/ plaintext syntax which cause security issue. You should add possibility to get credentials from a k8s secret.

**Comment by hiddeco** [comment]
It is possible to securely provide the credentials by mounting a custom Helm repository index from a secret, the expected path for this file is `/var/fluxd/helm/repository/repositories.yaml`.

**Comment by Francois-Royer** [comment]
Ok, I miss that in documentations. Thanks !

**Comment by Francois-Royer** [comment]
So I manage to mount /var/fluxd/helm/repository/repositories.yaml into flux-helm-operator pod from a secret that contain my private repository, but I still not able to use it. What should I put in  helmrelease to use repo from  /var/fluxd/helm/repository/repositories.yaml file ?

**Comment by hiddeco** [comment]
Given your repository index file looks like the following, and your chart is called `my-chart`:

```yaml
apiVersion: v1
repositories:
- caFile: ""
  cache: /var/fluxd/helm/repository/cache/my-private-registry-index.yaml
  certFile: ""
  keyFile: ""
  name: my-private-registry
  password: "some-password"
  url: https://my-private-registry.com
  username: "some-username"
...
```

your `HelmRelease` `spec.chart` entry should look like:

```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
...
spec:
  ...
  chart:
    repository: https://my-private-registry.com
    name: my-chart
    version: 1.2.3
...
```
