### ISSUE TITLE
nil pointer evaluating interface {}.jwk

### ISSUE THREAD

**Issue by adurai81** [fluxcd/helm-operator#143]
**Describe the bug**

I'm trying to helm install istio. Trying to perform dry run fails with this error.

```
Error: render error in "istio/charts/security/templates/configmap.yaml": template: istio/charts/security/templates/configmap.yaml:17:10: executing "istio/charts/security/templates/configmap.yaml" at <include "security-permissive.yaml.tpl" .>: error calling include: template: istio/charts/security/templates/enable-mesh-permissive.yaml:16:26: executing "security-permissive.yaml.tpl" at <.Values.authN.jwk>: nil pointer evaluating interface {}.jwk
```

I've this in my values.yaml file

```
#
# jwks for Authentication
#
# The value REPLACE_JWKS is expected to be replaced with actual value at the time of deployment
#
#
authN:
  jwk: test12345
```

and the referencing code looks like this 

```
{{- define "security-permissive.yaml.tpl" }}
# Authentication policy to enable permissive mode for all services (that have sidecar) in the mesh.
apiVersion: "authentication.istio.io/v1alpha1"
kind: "MeshPolicy"
metadata:
  name: "default"
  labels:
    app: {{ template "security.name" . }}
    chart: {{ template "security.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  origins:
  - jwt:
      issuer: "https://identity.oraclecloud.com/"
      jwksUri: "{{ .Values.authN.jwk }}"
  principalBinding: USE_ORIGIN
  peers:
  - mtls:
      mode: PERMISSIVE
{{- end }}
```

**To Reproduce**
Steps to reproduce the behaviour:

This is how I'm testing -
`helm install --debug --dry-run . --namespace istio-system`

**Expected behavior**
helm dry run should have passed.

**Logs**
None

**Additional context**
Add any other context about the problem here, e.g 
- Helm operator version: 
```
Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```
- Kubernetes version:
```
Client Version: v1.15.3
Server Version: v1.13.5-6+d6ea2e3ed7815b
```
- Git provider:

- Container registry provider:
Oracle Cloud Infrastructure
