### ISSUE TITLE
Tiller timeout

### ISSUE THREAD

**Issue by alexanderbuhler** [fluxcd/helm-operator#144]
So this probably is not a bug, but I'm not sure on where to put this so I'll start with helm operator. 😩 

Never had issues installing istio, but some stuff changed over the last weeks (k8s updates, tiller updates) and suddenly I cannot install/upgrade my istio helmrelease any more. Is there a way to modify that timeout? what does it even mean, after all?

Grateful for any hints on how to debug this issue. Thanks. 

**Logs**
```
ts=2019-12-11T21:43:04.275846203Z caller=release.go:216 component=release error="Chart release failed: istio: &status.statusError{Code:2, Message:\"release istio failed: Timeout: request did not complete within requested timeout 30s\", Details:[]*any.Any(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}"
```
**Additional context**
Add any other context about the problem here, e.g 
- Helm operator version: 1.0.0-rc4
- Kubernetes version: 1.15.6
- Tiller: 2.16.1

**Comment by hiddeco** [comment]
You can set the timeout to a higher value by defining `spec.timeout`, the value should be an integer and equals to seconds.

**Comment by alexanderbuhler** [comment]
Alright, thanks.

Looks like this now:
```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: istio
  namespace: istio-system
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: istio
  timeout: 120
  chart:
    repository: https://storage.googleapis.com/istio-release/releases/1.4.2/charts
    name: istio
    version: 1.4.2
  values:
```

Error message from helm operator stays the same, though. Comes right after 30s.
