### ISSUE TITLE
helm operator does not work with chart source git anymore "No requirements found in..."

### ISSUE THREAD

**Issue by runningman84** [fluxcd/helm-operator#162]
**Describe the bug**
The helm operator does not work with chart source git anymore. This used to work fine before. I have followed all upgrade steps outlined in these docs:
https://docs.fluxcd.io/projects/helm-operator/en/latest/guides/upgrading-to-ga.html

**To Reproduce**
Steps to reproduce the behaviour:
1. install chart helm-operator-0.4.0 with version1.0.0-rc5
2. configure a custom helm chart using git
3. watch for errors

**Expected behavior**
The sync should work fine as before

**Logs**
If applicable, please provide logs. In a standard stand-alone installation, you'd get this by running `kubectl logs -n default deploy/flux-helm-operator`.
```
ts=2019-12-25T21:25:09.821293469Z caller=logwriter.go:28 component=helm version=v2 info="No requirements found in /tmp/flux-working647662783/mosquitto/charts."
ts=2019-12-25T21:25:10.925851102Z caller=release.go:254 component=release release=mosquitto targetNamespace=hass resource=hass:helmrelease/mosquitto helmVersion=v2 info="Helm release sync succeeded" revision=63879ace4d876487e76b7751d6ffbff9ae0123c6
ts=2019-12-25T21:26:23.543191483Z caller=operator.go:309 component=operator info="enqueuing release" resource=hass:helmrelease/mosquitto
ts=2019-12-25T21:26:37.99781462Z caller=logwriter.go:28 component=helm version=v2 info="No requirements found in /tmp/flux-working261636912/mosquitto/charts."
ts=2019-12-25T21:29:23.530004606Z caller=operator.go:309 component=operator info="enqueuing release" resource=hass:helmrelease/mosquitto
ts=2019-12-25T21:29:23.59975444Z caller=logwriter.go:28 component=helm version=v2 info="No requirements found in /tmp/flux-working549726262/mosquitto/charts."
ts=2019-12-25T21:32:23.552139866Z caller=operator.go:309 component=operator info="enqueuing release" resource=hass:helmrelease/mosquitto
ts=2019-12-25T21:32:49.494363343Z caller=logwriter.go:28 component=helm version=v2 info="No requirements found in /tmp/flux-working442993767/mosquitto/charts."
ts=2019-12-25T21:35:23.537932098Z caller=operator.go:309 component=operator info="enqueuing release" resource=hass:helmrelease/mosquitto
ts=2019-12-25T21:35:36.021213276Z caller=logwriter.go:28 component=helm version=v2 info="No requirements found in /tmp/flux-working343676880/mosquitto/charts."
ts=2019-12-25T21:38:23.538669157Z caller=operator.go:309 component=operator info="enqueuing release" resource=hass:helmrelease/mosquitto
ts=2019-12-25T21:38:32.464402194Z caller=logwriter.go:28 component=helm version=v2 info="No requirements found in /tmp/flux-working027199338/mosquitto/charts."
ts=2019-12-25T21:41:23.537499034Z caller=operator.go:309 component=operator info="enqueuing release" resource=hass:helmrelease/mosquitto
ts=2019-12-25T21:41:31.720450303Z caller=logwriter.go:28 component=helm version=v2 info="No requirements found in /tmp/flux-working436450467/mosquitto/charts."

```

HelmRelease:
```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: hass
  annotations:
    flux.weave.works/automated: 'true'
spec:
  releaseName: mosquitto
  chart:
    git: git@github.com:runningman84/helm-charts.git
    ref: master
    path: mosquitto
  values:
    name: mosquitto
```

**Additional context**
Add any other context about the problem here, e.g 
- Helm operator version: 1.0.0 rc5
- Kubernetes version: k3s 1.0
- Git provider: github
- Container registry provider: docker hub

**Comment by runningman84** [comment]
This might be a similar issue:
```
ts=2019-12-25T21:47:42.354583057Z caller=release.go:128 component=release release=external-auth-server targetNamespace=kube-system resource=kube-system:helmrelease/external-auth-server helmVersion=v2 error="failed updating dependencies" err="could not find /tmp/flux-working269442335/chart: stat /tmp/flux-working269442335/chart: no such file or directory"
```
This is the corresponding HelmRelease:
```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: external-auth-server
  namespace: kube-system
spec:
  releaseName: external-auth-server
  chart:
    git: git@github.com:travisghansen/external-auth-server.git
    ref: master
    path: chart
  values:
    name: external-auth-server
```
