### ISSUE TITLE
Chart lookup fails and appears to be looking in the wrong cache

### ISSUE THREAD

**Issue by palemtnrider** [fluxcd/helm-operator#164]
**Describe the bug**
Using 0.4.0 (1.0.0-rc5) and the podinfo hr doesn't load with the following error:
`chart unavailable: no cached repo found. (try 'helm repo update'). open /var/fluxd/helm/repository/cache/stable-index.yaml: no such file or directory`

``` shell
cat <<EOF | kubectl apply -f -
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  releaseName: podinfo
  chart:
    repository: https://stefanprodan.github.io/podinfo
    version: 2.1.0
    name: podinfo
  values:
    replicaCount: 1
EOF
```

Switching back to 0.3.0 and the chart is loaded correctly.  

**To Reproduce**
Steps to reproduce the behaviour:
0. What's your setup?
helm 2
helm-operator chart 0.4.0
minikube
`helm install --wait --name helm-operator \
--namespace fluxcd \
fluxcd/helm-operator `
``` shell
helm upgrade -i helm-operator fluxcd/helm-operator \
--namespace fluxcd \
--set configureRepositories.enable=true \
--set configureRepositories.repositories[0].name=stable \
--set configureRepositories.repositories[0].url=https://kubernetes-charts.storage.googleapis.com \
--set configureRepositories.repositories[1].name=podinfo \
--set configureRepositories.repositories[1].url=https://stefanprodan.github.io/podinfo
```
2. Click on 
add hr
``` shell
cat <<EOF | kubectl apply -f -
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  releaseName: podinfo
  chart:
    repository: https://stefanprodan.github.io/podinfo
    version: 2.1.0
    name: podinfo
  values:
    replicaCount: 1
EOF
```
3. Scroll down to 
`kubectl describe hr podinfo`

**Expected behavior**
The podinfo chart to be deployed or the error to reference the podinfo cache not the stable cache

**Logs**
If applicable, please provide logs. In a standard stand-alone installation, you'd get this by running `kubectl logs -n default deploy/flux-helm-operator`.

**Additional context**
Switching back to 0.3.0 fixed the issue.

See slack discussion at https://weave-community.slack.com/archives/C4U5ATZ9S/p1577392027025900

**Comment by davidkarlsen** [comment]
I am seeing the same. Could it be because I use several repos?

**Comment by davidkarlsen** [comment]
Hmm, could it be that update of one repo affects the others?
I see:
```
status:
  conditions:
  - lastTransitionTime: "2019-11-16T14:16:23Z"
    lastUpdateTime: "2019-12-14T16:01:41Z"
    message: helm upgrade succeeded
    reason: HelmSuccess
    status: "True"
    type: Released
  - lastTransitionTime: "2019-12-23T23:33:59Z"
    lastUpdateTime: "2019-12-28T15:14:00Z"
    message: 'chart unavailable: no cached repo found. (try ''helm repo update'').
      open /var/fluxd/helm/repository/cache/fluxcd-index.yaml: no such file or directory'
    reason: RepoFetchFailed
    status: "False"
    type: ChartFetched
  observedGeneration: 11
```
which should not matter for this chart which is a bitnami one.

**Comment by davidkarlsen** [comment]
and after a while:
```
status:
  conditions:
  - lastTransitionTime: "2019-11-16T14:16:23Z"
    lastUpdateTime: "2019-12-14T16:01:41Z"
    message: helm upgrade succeeded
    reason: HelmSuccess
    status: "True"
    type: Released
  - lastTransitionTime: "2019-12-23T23:33:59Z"
    lastUpdateTime: "2019-12-28T17:01:55Z"
    message: 'chart unavailable: no cached repo found. (try ''helm repo update'').
      open /var/fluxd/helm/repository/cache/flagger-index.yaml: no such file or directory'
    reason: RepoFetchFailed
    status: "False"
    type: ChartFetched
  observedGeneration: 11
  releaseName: fluentd
  releaseStatus: deployed
  revision: 0.4.3
  valuesChecksum: 62b9a6f4d337781ee1dfc2d316e78d52609b888ac8af4fc6b96d9614ee3b0a59
```
