### ISSUE TITLE
Changing values.yaml in chart does not result in new deployment

### ISSUE THREAD

**Issue by stefansedich** [fluxcd/helm-operator#174]
**Describe the bug**
When changing a value inside the values.yaml for a referenced chart it appears as this change is not picked up and results in a new deployment not happening.

Given the following release:

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: podinfo-dev
  chart:
    git: https://github.com/stefansedich/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values: {}
```

If I were to then go and update the `replicaCount` in the charts values.yaml I would expect a deployment to happen but after a number of sync cycles nothing happens. If I were to go change something inside say `templates/deployment.yaml` however this does get picked up.

**To Reproduce**
Steps to reproduce the behaviour:
1. Deploy the above release (you might want to deploy pointing to a fork you can edit)
2. Change replicaCount to another value
3. Wait 5 minutes
4. Witness no deployment has happened updating replica count

**Expected behavior**
I would expect a change in values.yaml would result in a release to happen, especially in this case where it is something like number of replicas changing.

**Logs**
Nothing special shown in the logs, just normal sync happening.

**Additional context**
Add any other context about the problem here, e.g 
- Helm operator version: rc5
- Targeted Helm version: 3.0.1
- Kubernetes version: 1.14.6
- Git provider: GitHub
- Container registry provider: N/A
