### ISSUE TITLE
nested helm variables

### ISSUE THREAD

**Issue by dzirg44** [fluxcd/helm-operator#208]
kubernetes flux

**Description**

I faced with some problems with nested variables.
i have a release
```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: php-api
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.php-api-cronjob-organisations: glob:test-dev-*
    repository.fluxcd.io/php-api-cronjob-organisations: cronjob.organisations.image
spec:
  releaseName: php-api-dev
  chart:
    git: git@github.com:flux/fluxcmd.git
    path: charts/php
    ref: master
  values:
    cronjob:
      organisations:
        image: "11111111.dkr.ecr.eu-west-5.amazonaws.com/test-dev-php-api:76"
```
but flux cannot update nested images.
I read about `helm-operator-integration` but it works only if I run release with `--force` flag. In other case I receive a message that I don't have any changes in my repo. Maybe i didn't understand this article...

**Expected behavior**
Updated images.

**Additional context**

- Helm operator version: 0.2.1
- Flux version: 1.14.2
- Kubernetes version: 1.5
- Git provider: github
- Container registry provider: aws-ecr

Thank you for your help.

**Comment by hiddeco** [comment]
The problem is that your tag does not match the configured filter, I expect Flux' automation to work just fine if you change the image tag in the `.spec.values` to one that adheres to the filter (this is why `--force` _does_ work).

**Comment by dzirg44** [comment]
@hiddeco thank you for explanation, i will try tomorrow. If you don't mind , please don't close this question i want to write a conclusion.

**Comment by dzirg44** [comment]
yep, I made a mistake, i my case it has to be like
```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: php-api
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.php-api-cronjob-organisations: glob:*
    repository.fluxcd.io/php-api-cronjob-organisations: cronjob.organisations.image
spec:
  releaseName: php-api-dev
  chart:
    git: git@github.com:flux/fluxcmd.git
    path: charts/php
    ref: master
  values:
    cronjob:
      organisations:
        image: "11111111.dkr.ecr.eu-west-5.amazonaws.com/test-dev-php-api:76"
```
however  in case when i have
```
'glob: *'
```
it didn't work. maybe because of whitespace , i don't know.

**Comment by stefanprodan** [comment]
You could migrate to the new annotations:
```yaml
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: php-api
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/cronjob: glob:*
    repository.fluxcd.io/cronjob: cronjob.organisations.image
spec:
  releaseName: php-api-dev
  chart:
    git: git@github.com:flux/fluxcmd.git
    path: charts/php
    ref: master
  values:
    cronjob:
      organisations:
        image: "11111111.dkr.ecr.eu-west-5.amazonaws.com/test-dev-php-api:76"
```
