### ISSUE TITLE
repeated upgrades with helm operator even though there is no change 

### ISSUE THREAD

**Issue by sureshamk** [fluxcd/helm-operator#218]
**Describe the bug**
I have 3 helm releases , out of one is upgrading every min even though the there is no change made  

**Logs**

<img width="1184" alt="Screen Shot 2020-01-17 at 6 21 04 PM" src="https://user-images.githubusercontent.com/3139449/72613905-de6ede80-3956-11ea-88b0-b46da745a41d.png">

**Additional context**
Add any other context about the problem here, e.g 
- Helm operator version: 
   ```docker.io/fluxcd/helm-operator:1.0.0-rc7```   
- Git provider:
   bitbucket
- Container registry provider:
   acr

Kind of same issue https://github.com/fluxcd/helm-operator/issues/8#issuecomment-574389970

Is there any workaround to solve this kind of issue ?

**Comment by hiddeco** [comment]
Can you please provide me with a copy of the logs related to this release, a (redacted) copy of the `HelmRelease`, and some information about the chart you are using, especially if you set any annotations and/or labels that differ every time a release (or dry-run) happens.

**Comment by sureshamk** [comment]
@hiddeco I was suspected , might be dependencies causing the issue. I removed the **requirements.yaml** ,  no repeated upgrades for the release. When add the **requirements.yaml** i am able to reproduce the issue.  I am included the used requirements.yaml


```
#requirements.yaml
dependencies:
  - name: redis
    version: 5.3.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: dependencies.redis.enabled
```
