### ISSUE TITLE
helm: support (repository) getter plugins

### ISSUE THREAD

**Issue by cbenjemaa** [fluxcd/helm-operator#228]
**Describe the feature**
After a discussion with @hiddeco on [slack](https://cloud-native.slack.com/archives/CLAJ40HV3/p1578404117005000) about an issue that encountered when creating `HelmRelease` with a chart that has dependency chart hosted in google bucket under `gs://...` like URL.
```yaml
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: servicename
  namespace: default
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.stable: semver:5.x
    flux.weave.works/tag.canary: glob:v*
spec:
  releaseName: servicename
  chart:
    git: git@github.com:company/servicename
    path: deployment/servicename
    ref: master
  values:
    stable:
      image:
        repository: eu.gcr.io/gcs-helm-repo-id/company/servicename
        tag: v1.0.1
      replicaCount: 2
    canary:
      image:
        repository: eu.gcr.io/gcs-helm-repo-id/company/servicename
        tag: v1.0.1
      replicaCount: 1
```
The chart in `git@github.com:company/servicename` contains `requirements.yaml` file that looks like: 
```yaml
dependencies:
  - name: dependency
    version: 0.0.1
    repository: gs://gcs-helm-repo-id
```

So in that case the operator isn't able to handle the chart in `gs://gcs-helm-repo-id` sinceit   supports only HTTP(S) and local references `file://` and it logs the following:
```json
ts=2020-01-07T13:08:42.015422132Z caller=chartsync.go:546 component=chartsync warning="failed to update chart dependencies" resource=default:helmrelease/servicename err="could not update repo: Error: Could not find protocol handler for: gs\n"
```

Would that be beneficial for other users as well ? 

And in case I'd like to work on that what are packages/file of the operator that I need to understand and change? 

Appreciate your time :)
