### ISSUE TITLE
Cluster autoscaler reports "error validating \"\": error validating data: [apiVersion not set, kind not set]"" for cluster-autoscaler chart

### ISSUE THREAD

**Issue by cep21** [fluxcd/helm-operator#254]
**Describe the bug**

I cannot install cluster-autoscaler(https://github.com/helm/charts/tree/master/stable/cluster-autoscaler) with helm-operator if I use serviceAccountAnnotations.  If I remove `serviceAccountAnnotations` from my yaml, the install works via helm-operator.  if I install manually with helm (and include serviceAccountAnnotations), it also works.

**To Reproduce**
These are my flux versions
```
< helm list -a --all-namespaces | grep flux                                                                                             
flux                            flux            2               2020-01-28 04:29:08.248999609 +0000 UTC deployed        flux-1.1.0              1.17.1                                                                                                                          
helm-operator                   flux            3               2020-01-29 00:29:33.722840817 +0000 UTC deployed        helm-operator-0.6.0     1.0.0-rc8                                                                                                                       
```

This is my yaml file in my git repository
```
< cat cluster-autoscaler.yaml                                                                                                                                                                                                                                                   
---                                                                                                                                                                                                                                                                             
apiVersion: helm.fluxcd.io/v1                                                                                                                                                                                                                                                   
kind: HelmRelease                                                                                                                                                                                                                                                               metadata:                                                                                                                                                                                                                                                                       
  name: cluster-autoscaler                                                                                                                                                                                                                                                      
  namespace: kube-system                                                                                                                                                                                                                                                        
spec:                                                                                                                                                                                                                                                                             chart:                                                                                                                                                                                                                                                                        
    repository: https://kubernetes-charts.storage.googleapis.com/                                                                                                                                                                                                               
    name: cluster-autoscaler                                                                                                                                                                                                                                                    
    version: 6.2.0                                                                                                                                                                                                                                                                values:                                                                                                                                                                                                                                                                       
    awsRegion: us-west-2                                                                                                                                                                                                                                                        
    rbac:                                                                                                                                                                                                                                                                       
      enabled: true                                                                                                                                                                                                                                                             
      serviceAccountAnnotations:                                                                                                                                                                                                                                                
        eks.amazonaws.com/role-arn: arn:aws:iam::12345:role/test                                                                                                                                                                                                                
    autoDiscovery:                                                                                                                      
      clusterName: ops          
```

This is what's in my helm-operator logs
```
< kubectl logs -n flux helm-operator-86b64777f9-tzzm6 | grep cluster-autoscaler | tail                                                                                                                                                                                          
ts=2020-01-29T00:29:46.587342784Z caller=release.go:214 component=release release=kube-system-cluster-autoscaler targetNamespace=kube-system resource=kube-system:helmrelease/cluster-autoscaler helmVersion=v3 error="Helm release failed" revision=6.2.0 err="failed to upgrad
e chart for release [kube-system-cluster-autoscaler]: unable to build kubernetes objects from release manifest: error validating \"\": error validating data: [apiVersion not set, kind not set]"                                                                               
ts=2020-01-29T00:32:42.630679927Z caller=operator.go:307 component=operator info="enqueuing release" resource=kube-system:helmrelease/cluster-autoscaler                                                                                                                        
ts=2020-01-29T00:32:44.133906566Z caller=release.go:317 component=release release=kube-system-cluster-autoscaler targetNamespace=kube-system resource=kube-system:helmrelease/cluster-autoscaler helmVersion=v3 info="no existing release" action=install
ts=2020-01-29T00:32:44.504661762Z caller=release.go:214 component=release release=kube-system-cluster-autoscaler targetNamespace=kube-system resource=kube-system:helmrelease/cluster-autoscaler helmVersion=v3 error="Helm release failed" revision=6.2.0 err="failed to upgrad
e chart for release [kube-system-cluster-autoscaler]: unable to build kubernetes objects from release manifest: error validating \"\": error validating data: [apiVersion not set, kind not set]"
ts=2020-01-29T00:35:42.630092337Z caller=operator.go:307 component=operator info="enqueuing release" resource=kube-system:helmrelease/cluster-autoscaler
ts=2020-01-29T00:35:42.642576584Z caller=release.go:317 component=release release=kube-system-cluster-autoscaler targetNamespace=kube-system resource=kube-system:helmrelease/cluster-autoscaler helmVersion=v3 info="no existing release" action=install
ts=2020-01-29T00:35:42.916172263Z caller=release.go:214 component=release release=kube-system-cluster-autoscaler targetNamespace=kube-system resource=kube-system:helmrelease/cluster-autoscaler helmVersion=v3 error="Helm release failed" revision=6.2.0 err="failed to upgrad
e chart for release [kube-system-cluster-autoscaler]: unable to build kubernetes objects from release manifest: error validating \"\": error validating data: [apiVersion not set, kind not set]"
ts=2020-01-29T00:38:42.630618383Z caller=operator.go:307 component=operator info="enqueuing release" resource=kube-system:helmrelease/cluster-autoscaler
ts=2020-01-29T00:38:43.199005506Z caller=release.go:317 component=release release=kube-system-cluster-autoscaler targetNamespace=kube-system resource=kube-system:helmrelease/cluster-autoscaler helmVersion=v3 info="no existing release" action=install
ts=2020-01-29T00:38:43.460623289Z caller=release.go:214 component=release release=kube-system-cluster-autoscaler targetNamespace=kube-system resource=kube-system:helmrelease/cluster-autoscaler helmVersion=v3 error="Helm release failed" revision=6.2.0 err="failed to upgrad
e chart for release [kube-system-cluster-autoscaler]: unable to build kubernetes objects from release manifest: error validating \"\": error validating data: [apiVersion not set, kind not set]"
```
This command shows no install
```
> helm list -a --all-namespaces | grep cluster-auto
```

This is a values.yaml if I try to install manually

```
< cat values.yaml 
awsRegion: us-west-2
rbac:
  enabled: true
  serviceAccountAnnotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::12345:role/test
autoDiscovery:
  clusterName: ops
```

This is me running the helm command manually and it working
```
> helm install kube-system-cluster-autoscaler stable/cluster-autoscaler -f values.yaml 
NAME: kube-system-cluster-autoscaler
LAST DEPLOYED: Wed Jan 29 00:40:51 2020
NAMESPACE: kube-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
To verify that cluster-autoscaler has started, run:

  kubectl --namespace=kube-system get pods -l "app=aws-cluster-autoscaler,release=kube-system-cluster-autoscaler"
```

This is what helm sees the values as after I install manually with the helm CLI.

```
< helm get values kube-system-cluster-autoscaler
USER-SUPPLIED VALUES:
autoDiscovery:
  clusterName: ops
awsRegion: us-west-2
rbac:
  enabled: true
  serviceAccountAnnotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::12345:role/test
```
This is my helm version
```
< helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}
```

**Expected behavior**
I expect helm-operator to install the chart just like I can with the helm CLI
