### ISSUE TITLE
chart: offer support for Helm (getter) plugin init containers

### ISSUE THREAD

**Issue by hiddeco** [fluxcd/helm-operator#267]
Support for Helm (getter) plugins has been worked on in #263 and will be merged soon. The mentioned PR does however not make the functionalities easily accessible using our Helm chart.

To best way in my opinion to make them accessible using the chart would be to create some dynamic method that is able to generate plugin installing init containers using the following format:

```yaml
pluginInitContainers:
- helmVersion: v2
  plugin: https://github.com/hypnoglow/helm-s3.git
  version: 0.9.2
- helmVersion: v3
  plugin: https://github.com/hayorov/helm-gcs
  version: 0.3.0
```

This would result in the definition of two `initContainers` entries for the Helm operator deployment:

```yaml
initContainers:
- name: helm-v2-plugin-helm-s3
  image: docker.io/fluxcd/helm-operator:1.0.0-rc8
  command: ['sh', '-c', 'helm2 plugin install https://github.com/hypnoglow/helm-s3.git --version 0.9.2']
  # Helm home mount entry
- name: helm-v3-plugin-helm-gcs
  image: docker.io/fluxcd/helm-operator:1.0.0-rc8
  command: ['sh', '-c', 'helm3 plugin install https://github.com/hayorov/helm-gcs --version 0.3.0']
  # Helm home mount entry
```
