### ISSUE TITLE
using alias in HelmRelease.spec.chart.repository

### ISSUE THREAD

**Issue by Fapfood** [fluxcd/helm-operator#274]
I tried to use alias in HelmRelease.spec.chart.repository. I created secret with our repositories.yml and uncommented both volumes: for repositories and for cache. Unfortunately alias is not parsed. I got this error:
`caller=release.go:140 component=release release=prometheus targetNamespace=prometheus resource=prometheus:helmrelease/prometheus helmVersion=v3 erro
r="chart unavailable: could not find protocol handler for: "`
However when I put actual URL in repository everything works (`repository: https://github.company.com/pages/helm-charts`).
The problem may come from that comparision: https://github.com/fluxcd/helm-operator/blob/master/pkg/helm/v3/pull.go#L54. In my opinion it should compare repoURL with entry.Name.
```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
  annotations:
    fluxcd.io/automated: "true"
spec:
  chart:
    name: prometheus-operator
    #repository: https://github.company.com/pages/helm-charts 
    repository: stable 
    version: 8.2.0
  releaseName: prometheus
  values:
```

```
apiVersion: v1
repositories:
- caFile: ""
  cache: /var/fluxd/helm/repository/cache/stable-index.yaml
  certFile: ""
  keyFile: ""
  name: stable
  password: ""
  url: https://github.company.com/pages/helm-charts 
  username: ""
```
