### ISSUE TITLE
Helm Chart Deploys, but not updating and error in helm-operator log

### ISSUE THREAD

**Issue by boocup** [fluxcd/helm-operator#275]
**Describe the bug**

My app deploys, but won't update. Flux log looks ok, but error in helm-operator log

**To Reproduce**

helm upgrade -i flux fluxcd/flux \
--set git.url="git@github.com:boocup/Tidal-SaaS-653" \
--set git.branch="flux-setup-test" \
--namespace flux

helm upgrade -i helm-operator fluxcd/helm-operator \
--set git.ssh.secretName=flux-git-deploy \
--namespace flux

**Expected behavior**

After app launches, helm-operator can connect to git repo.

**Logs**

**flux logs look ok**

 component=sync-loop event=refreshed url=ssh://git@github.com/boocup/Tidal-SaaS-653 branch=flux-setup-test HEAD=b824641cd246d0e9db71177764aa46a9048a48d2

**helm-operator logs with error**
component=gitchartsync info="started mirroring new remote" remote=ssh://git@github.com/boocup/Tidal-SaaS-653 mirror=ssh://git@github.com/boocup/Tidal-SaaS-653

component=release release=tidal targetNamespace=default resource=default:helmrelease/tidal helmVersion=v2 error="chart not ready: no existing git mirror found"

**Additional context**

- Helm operator version:  2.13
- Kubernetes version: 1.15
- Git provider: GitHub.com

**Comment by stefanprodan** [comment]
Can you post here the HelmRelease file?

**Comment by boocup** [comment]
absolutely...thank you!

```yaml
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: tidal
  namespace: default
spec:
  releaseName: tidal
  chart:
    git: ssh://git@github.com/boocup/Tidal-SaaS-653
    ref: flux-setup-test
    path: charts/tidal
```
