### ISSUE TITLE
Installation of s3 plugin fails on master b/c of lack of bash

### ISSUE THREAD

**Issue by cep21** [fluxcd/helm-operator#283]
**Describe the bug**

Unable to start a helm-operator with the s3 plugin as documented.

**To Reproduce**

Try installing the s3 plugin on master

**Expected behavior**

S3 plugin works

**Additional context**

Execute the following
```
    docker run -it --entrypoint=/bin/sh docker.io/fluxcd/helm-operator:1.0.0-rc8
```

When inside a terminal execute
```
/home/flux # helm3 plugin list
NAME    VERSION DESCRIPTION
/home/flux # helm3 plugin install https://github.com/hypnoglow/helm-s3.git --version v0.9.2
env: can't execute 'bash': No such file or directory
Error: plugin install hook for "s3" exited with error
/home/flux # which env
/usr/bin/env
/home/flux # helm3 plugin list
NAME    VERSION DESCRIPTION                                                                                
s3      0.9.2   The plugin allows to use s3 protocol to upload, fetch charts and to work with repositori...
/home/flux # 
```

Notice how the plugin installs, but with an error on the post install hook at https://github.com/hypnoglow/helm-s3/blob/master/hack/install.sh which requires bash 

This causes an exit code 1 which fails the pod starting.  After that, future attempts to start the pod fail because

```
< kubectl --namespace=flux logs helm-operator-6cd68548bd-jq774 helm-plugin-init-00 
Error: plugin already exists
```

**Comment by cep21** [comment]
The end result of all of this is that a deployment of helm operator for the initContainers won't pass
```
      initContainers:
      - command:
        - sh
        - -c
        - helm3 plugin install https://github.com/hypnoglow/helm-s3.git --version
          v0.9.2
    image: docker.io/fluxcd/helm-operator:1.0.0-rc8
```
