### ISSUE TITLE
Seems to not update charts; keeps trying to process old HelmRelease and chart yaml

### ISSUE THREAD

**Issue by rally25rs** [fluxcd/helm-operator#288]
**Describe the bug**

I have a repo that contains `flux` + `helm chart` that is structured like:

```
this-repo
+- charts
    +- cloud-services
         +- Chart.yaml (and rest of chart files)
+- releases
    +- qa
         +- cloud-servies.yaml
```

The `releases/qa/cloud-services.yaml` contains

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cloud-services-qa # <-- NOTE: at some point I renamed this. It used to be `cloud-services-dev`
  namespace: qa
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: cloud-services-qa
  chart:
    git: git@github.com:this-org/this-repo
    path: charts/cloud-services
    ref: flux-test
```

The log from the `helm-operator` pod keeps printing out
```
ts=2020-02-11T18:27:48.611339048Z caller=operator.go:307 component=operator info="enqueuing release" resource=dev:helmrelease/cloud-services-dev

...

ts=2020-02-11T18:27:55.451521289Z caller=release.go:214 component=release release=cloud-services-dev targetNamespace=dev resource=dev:helmrelease/cloud-services-dev helmVersion=v3 error="Helm release failed" revision=ced3e475caf9f42b2976ed988775c904e838b09b err="failed to upgrade chart for release [cloud-services-dev]: ...
```
and then some errors processing the helm chart itself. I had since completely deleted the offending bit of helm chart code, but it keeps reporting the code as an error, even though it no longer exists. The `release` and `namespace` are also both still reporting `dev` but those do not exist any more in the Flux `releases/` directories

**To Reproduce**

I'm not entirely sure what I did to get into this state. We had attempted to deploy under a `dev` release (which never deployed successfully), then renamed that directory and names in the yaml to `qa`, but `helm-operator` appears to keep trying to process a no-longer-existing `dev` release.

**Expected behavior**

Should re-clone the `git@github.com:this-org/this-repo` `flux-test` branch and run with the new `HelmRelease`.

Should not be trying to process a `HelmRelease` that no longer exists.

**Logs**
log snippet above

**Additional context**

- Helm operator version: `Image:      docker.io/fluxcd/helm-operator:1.0.0-rc8` installed with `helm upgrade -i helm-operator fluxcd/helm-operator` on Feb. 7th.
- Kubernetes version:
- Git provider:
- Helm repository provider: github url

-----

**Debugging Notes**

It's pretty hard to debug this stuff, but if I `sh` into the pod I can do
```
cd /tmp/flux-gitclone855103427
git log flux-test
```
to verify that the cloned git repo does have my latest commits (where `cloud-services-dev` no longer exists)

I'm trying to read through the code and see what this actually does between the close and the processing of the HelmRelease, but it's slow going...

-----

By removing the cached dir `/tmp/flux-gitclone*` I then see the error
```
ts=2020-02-11T20:06:48.620962002Z caller=operator.go:307 component=operator info="enqueuing release" resource=dev:helmrelease/cloud-services-dev
ts=2020-02-11T20:06:48.637564184Z caller=release.go:110 component=release release=cloud-services-dev targetNamespace=dev resource=dev:helmrelease/cloud-services-dev helmVersion=v3 error="chart unavailable: chdir /tmp/flux-gitclone855103427: no such file or directory"
```

So it looks like it gets this non-existant `release=cloud-services-dev targetNamespace=dev` before doing the clone.

Anyone know what calls `operator.go`? I guess I'm not entirely sure how `flux` sends requests to `helm-operator`, but maybe this is a `flux` problem?
