### ISSUE TITLE
Restricted keyword "role" in values.yaml file

### ISSUE THREAD

**Issue by ma-groundspeed** [fluxcd/helm-operator#309]
**Describe the bug**
(Not sure if this exists in both v2 and v3, but I am currently using v3)

I have a deployment file where I have an annotation on it like the following:
```yaml
spec:
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: "{{ .Values.role }}"
```

Where my values.yaml file looks like:
```yaml
role: "arn:aws:iam::XXXXXXXXXX:role/test-role"
```

When using the key "role" in the values.yaml file, the template renders just fine using helm v3 locally, but when being deployed via the operator it turns the annotation into a `map`, see describe from the pod that gets created:
```
Annotations:  iam.amazonaws.com/role: map[iam.amazonaws.com/role:arn:aws:iam::XXXXXXXXXX:role:role/test-role]
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Use the above mentioned yaml and use the keyword "role" in your values.yaml file as an annotation.
2. Use the following chart versions for flux and helm-operator with helm v3: 
    - chart=helm-operator-0.7.0 (docker.io/fluxcd/helm-operator:1.0.0-rc9)
    - chart=flux-1.2.0 (docker.io/fluxcd/flux:1.18.0)
3. Once it is deployed, describe the pod and see that it is treating the value as a `map`

**Expected behavior**
It should not be a map, since it is just a string.

**Logs**
No applicable logs.

**Additional context**
Add any other context about the problem here, e.g 
- Helm operator version: 1.0.0-rc9
- Targeted Helm version: v3
- Kubernetes version: client: v1.16.0 server: v.1.14.8-eks
- Git provider: github
- Container registry provider: ecr

**Comment by hiddeco** [comment]
@ma-groundspeed I created a chart with the following `templates/deployment.yaml`:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        iam.amazonaws.com/role: "{{ .Values.role }}"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
```

and the following default `values.yaml`:

```yaml
replicaCount: 1
image:
  repository: stefanprodan/podinfo
  tag: 2.3.0
  pullPolicy: IfNotPresent
role: ""
```

I then created a `HelmRelease` making use of this chart:

```yaml
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: annotation-map
  namespace: demo
spec:
  releaseName: annotation-map
  chart:
    repository: http://chartmuseum:8080
    name: annotation-map
    version: 0.1.0
  values:
    role: "arn:aws:iam::XXXXXXXXXX:role/test-role"
```

Waited for the Helm operator to perform the release and described the `Deployment`:

```
Name:                   annotation-map
Namespace:              demo
CreationTimestamp:      Thu, 05 Mar 2020 22:23:31 +0100
Labels:                 app.kubernetes.io/instance=annotation-map
Annotations:            deployment.kubernetes.io/revision: 1
                        helm.fluxcd.io/antecedent: demo:helmrelease/annotation-map
Selector:               app.kubernetes.io/instance=annotation-map
Replicas:               1 desired | 1 updated | 1 total | 0 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 25% max surge
Pod Template:
  Labels:       app.kubernetes.io/instance=annotation-map
  Annotations:  iam.amazonaws.com/role: arn:aws:iam::XXXXXXXXXX:role/test-role
...
```

Also described the `Pod` to be sure:

```
Name:           annotation-map-58ccdf947f-6tttv
Namespace:      demo
Priority:       0
Node:           helm-operator-e2e-1-control-plane/172.17.0.2
Start Time:     Thu, 05 Mar 2020 22:23:31 +0100
Labels:         app.kubernetes.io/instance=annotation-map
                pod-template-hash=58ccdf947f
Annotations:    iam.amazonaws.com/role: arn:aws:iam::XXXXXXXXXX:role/test-role
...
```

---

I do not observe the map issue you mention in all of the above. Can you please provide a chart and `HelmRelease` that produced the error for you so I can replicate it?
