### ISSUE TITLE
Values from HelmRelease not properly transferred to helm deployment

### ISSUE THREAD

**Issue by PeterGrace** [fluxcd/helm-operator#312]
**Describe the bug**
We are attempting to set environment variable via specific values specified in the HelmRelease, however some of the values are not properly populating into the deployment spec.

**To Reproduce**

Create a HelmRelease similar to the following:
```
  values:
    dataProviders:
      microsoft:
        appId: TEST1
        clientSecret: TEST2
```
Have a helm chart capable of receiving values specified:
```
$ helm template . --set dataProviders.microsoft.appId=TEST1 --set dataProviders.microsoft.clientSecret=TEST2
<...snip...>
            - name: DataProviders__Microsoft__AppId
              value: "TEST1"
            - name: DataProviders__Microsoft__ClientSecret
              value: "TEST2"
```
See that HelmRelease is properly describable in kubectl:
```
  $   kubectl describe helmrelease webapi
<...snip...>
    Data Providers:
      Microsoft:
        App Id:                    TEST1
        Client Secret:             TEST2
```
See that deployment does not reflect the values as shown in HelmRelease:
```
  $   kubectl get deployment -o yaml webapi
<...snip...>
      - env:
        - name: DataSource__Exchange
          value: data-source-exchange:8080
        - name: DataProviders__Microsoft__AppId
        - name: DataProviders__Microsoft__ClientSecret
        - name: CacheConfig__Enabled
          value: "false"
```

**Expected behavior**
The environment variables `DataProviders__Microsoft__AppId` and `DataProviders__Microsoft__ClientSecret` should have a key for value, with an appropriate value, in the env hash of the spec.template.spec.containers tree

**Logs**
No relevant log output generated at normal log levels.

**Additional context**
Add any other context about the problem here, e.g 
- Helm operator version: 1.0.0-rc9
- Targeted Helm version: v3
- Kubernetes version: 1.15.7
- Git provider: Azure DevOps
- Container registry provider: Azure Container Registry

**Comment by hiddeco** [comment]
Can you please provide a (pseudo) copy of the chart, or at least the template of the resource the env variables are in.

**Comment by PeterGrace** [comment]
Here's the deployment.yaml file with a few items redacted.  Relevant environment variables that are showing the issue are as-is and unedited.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "web-api.name" . }}
    helm.sh/chart: {{ include "web-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "web-api.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        {{- if .Values.annotations }}
        {{- .Values.annotations | toYaml | trimSuffix "\n" | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "web-api.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- if .Values.labels }}
        {{- .Values.labels | toYaml | trimSuffix "\n" | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- .Values.imagePullSecrets | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: api
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: api
          readinessProbe:
            httpGet:
              path: /api/health
              port: api
          env:
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:80"
            - name: DataSource__OneDrive
              value: "{{ .Values.dataSourceOneDriveHost }}"
            - name: DataSource__Exchange
              value: "{{ .Values.dataSourceExchangeHost }}"
            - name: DataSource__SharePoint
              value: "{{ .Values.dataSourceSharePointHost }}"
            - name: DataProviders__Microsoft__AppId
              value: "{{ .Values.dataProviders.microsoft.appId }}"
            - name: DataProviders__Microsoft__ClientSecret
              value: "{{ .Values.dataProviders.microsoft.clientSecret }}"
            - name: AccountManagementHost
              value: "{{ .Values.accountManagementHost }}"
            - name: SearchHost
              value: "{{ .Values.searchHost }}"
            - name: ViewSrcUrls__ReactBundleSrc
              value: "http://localhost:8082/bundle.js"
            - name: CacheConfig__Enabled
              value: "{{ .Values.api.cache.enable }}"
              {{- if .Values.development }}
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
              {{- end}}
          {{- if .Values.envFrom.enabled }}
          envFrom:
            {{- if .Values.envFrom.map.enabled }}
            - configMapRef:
                name: {{ .Values.envFrom.map.name }}
            {{- end }}
            {{- if .Values.envFrom.secret.enabled }}
            - secretRef:
                name: {{ .Values.envFrom.secret.name }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
```
