### ISSUE TITLE
Extend `chartFileRef` to support files from Helm repository chart sources

### ISSUE THREAD

**Issue by bitsofinfo** [fluxcd/helm-operator#315]
for this usage:

```
spec:
  # chart: ...
  valuesFrom:
  - chartFileRef:
      # path within the helm chart (from git repo) where environment-prod.yaml is located
      path: overrides/environment-prod.yaml # mandatory
      # If set to true successful retrieval of the values file is no
      # longer mandatory
      optional: true     
```
What does this path represent exactly. The comment implies that the yaml file is relative within the chart itself (i.e. embedded in the chart?). 

OR 

Does this mean a path relative from the location of the helm release `kind: HelmRelease` yaml file that this is declared in? i.e. in the same flux bound git repo that this release is in? 

basically its confusing to me.

So for this example below where is `overrides/environment-prod.yaml` expected to live?

Inside the chart itself?

In the git repo this helm release yaml lives in?

```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: myapp
  namespace: my-apps
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: myapp1
  chart:
    repository: https://raw.githubusercontent.com/bitsofinfo/appdeploy/master/repo
    name: appdeploy
    version: 1.1.15
  valuesFrom:
  - chartFileRef:
      path: overrides/environment-prod.yaml 
      optional: true     
  values:
    image:
      tag: 7.2
```
