### ISSUE TITLE
String values are interpreted as an integer

### ISSUE THREAD

**Issue by jbuettnerbild** [fluxcd/helm-operator#325]
**HelmRelease yaml**
In my HelmRelease yaml are a value for a image tag. The tag value is the short commit hash.

```
 values:
    global:
      image: xyz/foo/bar/dev
      tag: "0222e04"
```

**Deployment yaml**
And in the deployment i set the image tag also as label.

 ```
template:
    metadata:
      labels:
        tag: "{{ .Values.global.tag }}"
```
**Logs**
The release can't deployed with the log message: 
is invalid: spec.template.labels: Invalid value: \\\"2.22e+06\\\"

**Expected behavior**
If i template the chart lokal with helm the value will well interpreted. I had try to force the value as string by set:  tag: !!string 0222e04 but flux convert it to tag: "0222e04". I also had try some converting tricks in the template but thats all ugly and doesnt work good. 

When i set a value in a HelmRelease yaml with quotes i expect that the value are interpreted as a string value.

**Additional context**

- Helm operator version chart: 0.3.0
- Helm operator version: 1.0.0-rc4
- Kubernetes version: v1.14.9-eks-502bfb
- Git provider: github
- Helm repository provider: github
- helm version
Client: v2.9.1
Server: v2.16.1
