### ISSUE TITLE
Chart from git source fails to clone

### ISSUE THREAD

**Issue by Jeinhaus** [fluxcd/helm-operator#327]
**Describe the bug**

When using a HelmRelease with a git chart source, the release is not installed and the helm operator logs this error message:

```
fluxcd helm-operator-9885f9cc-6q9mf flux-helm-operator ts=2020-03-09T16:04:23.593174327Z caller=release.go:214 component=release release=victoria targetNamespace=planone-monitoring resource=planone-monitoring:helmrelease/victoria helmVersion=v3 error="Helm release failed" revision=b3d4bbc11414160a3928a0291c2bae263fc6b399 err="failed to load chart from path [/tmp/flux-working247361876/helm-charts/charts/victoria-metrics-single] for release [victoria]: stat /tmp/flux-working247361876/helm-charts/charts/victoria-metrics-single: no such file or directory"
```

**To Reproduce**

1. Example HelmRelease:

```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: victoria
  namespace: planone-monitoring
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: victoria
  resetValues: true
  chart:
    git: https://github.com/VictoriaMetrics/helm-charts.git
    ref: b3d4bbc11414160a3928a0291c2bae263fc6b399
    path: helm-charts/charts/victoria-metrics-single/
    skipDepUpdate: true
  values:
    server:
      retentionPeriod: 24
    persistentVolume:
      enabled: true
      size: 25Gi

```

2.  HelmRelease status:

```
Name:         victoria
Namespace:    planone-monitoring
Labels:       <none>
Annotations:  flux.weave.works/automated: false
              kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"helm.fluxcd.io/v1","kind":"HelmRelease","metadata":{"annotations":{"flux.weave.works/automated":"false"},"name":"victoria",...
API Version:  helm.fluxcd.io/v1
Kind:         HelmRelease
Metadata:
  Creation Timestamp:  2020-03-09T16:03:07Z
  Generation:          1
  Resource Version:    2060021
  Self Link:           /apis/helm.fluxcd.io/v1/namespaces/planone-monitoring/helmreleases/victoria
  UID:                 7765aa2f-621f-11ea-b1c7-0609bd73c6fe
Spec:
  Chart:
    Git:              https://github.com/VictoriaMetrics/helm-charts.git
    Path:             helm-charts/charts/victoria-metrics-single/
    Ref:              b3d4bbc11414160a3928a0291c2bae263fc6b399
    Skip Dep Update:  true
  Release Name:       victoria
  Reset Values:       true
  Values:
    Persistent Volume:
      Enabled:  true
      Size:     25Gi
    Server:
      Retention Period:  24
      Tolerations:
        Effect:    NoSchedule
        Key:       instanceType
        Operator:  Equal
        Value:     onDemand
Status:
  Conditions:
    Last Transition Time:  2020-03-09T16:03:09Z
    Last Update Time:      2020-03-09T16:03:09Z
    Message:               successfully cloned chart revision: b3d4bbc11414160a3928a0291c2bae263fc6b399
    Reason:                GitRepoCloned
    Status:                True
    Type:                  ChartFetched
    Last Transition Time:  2020-03-09T16:03:09Z
    Last Update Time:      2020-03-09T16:03:09Z
    Message:               failed to load chart from path [/tmp/flux-working072127806/helm-charts/charts/victoria-metrics-single] for release [victoria]: stat /tmp/flux-working072127806/helm-charts/charts/victoria-metrics-single: no such file or directory
    Reason:                HelmInstallFailed
    Status:                False
    Type:                  Released
  Observed Generation:     1
  Release Name:            
  Release Status:          
Events:
  Type    Reason       Age                From           Message
  ----    ------       ----               ----           -------
  Normal  ChartSynced  34s (x2 over 36s)  helm-operator  Chart managed by HelmRelease processed
```

**Expected behavior**

VictoriaMetrics Pods coming up or a helpful error message that allows me to fix the problem. 

**Logs**

```
fluxcd helm-operator-9885f9cc-6q9mf flux-helm-operator ts=2020-03-09T16:04:23.534838027Z caller=release.go:317 component=release release=victoria targetNamespace=planone-monitoring resource=planone-monitoring:helmrelease/victoria helmVersion=v3 info="no existing release" action=install
fluxcd helm-operator-9885f9cc-6q9mf flux-helm-operator ts=2020-03-09T16:04:23.593174327Z caller=release.go:214 component=release release=victoria targetNamespace=planone-monitoring resource=planone-monitoring:helmrelease/victoria helmVersion=v3 error="Helm release failed" revision=b3d4bbc11414160a3928a0291c2bae263fc6b399 err="failed to load chart from path [/tmp/flux-working247361876/helm-charts/charts/victoria-metrics-single] for release [victoria]: stat /tmp/flux-working247361876/helm-charts/charts/victoria-metrics-single: no such file or directory"

```

**Additional context**

I can clone the repo when exed into the pod.
I can install the chart when using `helm install`.

When execing into the helm-operator, `/tmp` does not contain any `flux-working...` directories. The folder looks like this:

```
/tmp # ls
flux-gitclone011257918  flux-gitclone071014161  flux-gitclone243696800  flux-gitclone740302538  flux-gitclone883475995  v3
```

- Helm operator version: :1.0.0-rc8
- Kubernetes version: v1.14.9-eks-502bfb
