### ISSUE TITLE
resetValues doesn

### ISSUE THREAD

**Issue by c4m4** [fluxcd/helm-operator#352]
**Describe the bug**

**To Reproduce**

Steps to reproduce the behaviour:
1. install a helm release manually with some extra values:
```
helm get values sig-app                        
image:
  pullPolicy: Always
  repository: docker.pkg.github.com/myorgxxx/docker-repo/sign-org-api
  tag: 0.0.5
imagePullSecret: github-pull
ingress:
  enabled: false
probe:
  liveness: /api/health/live
  readness: /api/health/ready
replicaCount: 2
runmigration: false
service:
  monitor: false
  type: ClusterIP
```

2. Provide a HelmRelease 
sig-app-release.yaml:
```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: docu-wrapper
  namespace: docu-wrapper
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~0.0
spec:
  releaseName: docu-wrapper
  resetValues: false
  forceUpgrade: false
  chart:
    git: git@github.com:myorgxxx/helm_charts.git
    path: java
    ref: master
  values:
    image:
      repository: docker.pkg.github.com/myorgxxx/docker-repo/sign-org-api
      pullPolicy: Always
      tag: 0.0.7
  rollback:
    enable: true
    wait: true

```
3. Post the HelmRelease status, you can get this by running `kubectl describe helmrelease <name>`
```
kubectl get hr -A                                                  
NAMESPACE      NAME           RELEASE        STATUS     MESSAGE   AGE
docu-wrapper   docu-wrapper   docu-wrapper   deployed             7m34s

kubectl describe hr -n docu-wrapper docu-wrapper
Name:         docu-wrapper
Namespace:    docu-wrapper
Labels:       fluxcd.io/sync-gc-mark=sha256.jZhD-QDe6MlgBJ_lb91nWXJYpQTeR8sDXDiWLcnE3EI
Annotations:  fluxcd.io/automated: true
              fluxcd.io/tag.chart-image: semver:~0.0
              kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"helm.fluxcd.io/v1","kind":"HelmRelease","metadata":{"annotations":{"fluxcd.io/automated":"true","fluxcd.io/tag.chart-image"...
API Version:  helm.fluxcd.io/v1
Kind:         HelmRelease
Metadata:
  Creation Timestamp:  2020-04-02T09:06:37Z
  Generation:          1
  Resource Version:    20811825
  Self Link:           /apis/helm.fluxcd.io/v1/namespaces/docu-wrapper/helmreleases/docu-wrapper
  UID:                 42580701-74c1-11ea-9ba0-4201ac10f406
Spec:
  Chart:
    Git:          git@github.com:myorgxxx/helm_charts.git
    Path:         java
    Ref:          master
  Force Upgrade:  false
  Release Name:   docu-wrapper
  Reset Values:   false
  Rollback:
    Enable:  true
    Wait:    true
  Values:
    Image: docker.pkg.github.com/myorgxxx/docker-repo/sign-org-api
      Pull Policy:  Always
      Repository:   
      Tag:          0.0.7
Status:
  Conditions:
    Last Transition Time:  2020-04-02T09:06:40Z
    Last Update Time:      2020-04-02T09:14:32Z
    Message:               successfully cloned chart revision: 5599e7e916e1aca185bfc523d18ed44189ea2876
    Reason:                GitRepoCloned
    Status:                True
    Type:                  ChartFetched
  Observed Generation:     1
  Release Name:            docu-wrapper
  Release Status:          pending-upgrade
Events:
  Type    Reason       Age                  From           Message
  ----    ------       ----                 ----           -------
  Normal  ChartSynced  4m7s (x4 over 9m2s)  helm-operator  Chart managed by HelmRelease processed

```
**Expected behavior**

To not reset the old values

Now everything is up and running, Let me try to push a new image to my registry:
**Logs**

```
docker push docker.pkg.github.com/myorgxxx/docker-repo/sign-org-api:0.0.8

helm get values docu-wrapper                                                           
image:
  pullPolicy: Always
  repository: docker.pkg.github.com/myorgxxx/docker-repo/sign-org-api
  tag: 0.0.8

kubectl get pods -n docu-wrapper | grep Imag
docu-wrapper-java-fc8c545c7-xphgz   0/1     ImagePullBackOff   0          4m21s
```

old values are begin removed and without credentials the image pull doesn't works
- Helm Operator version: helm-operator:1.0.0-rc9
- Kubernetes version: v1.14.10-gke.27
- Git provider: github
- Helm repository provider:
