### ISSUE TITLE
Pods not being recreated after ConfigMap/Secret checksum change

### ISSUE THREAD

**Issue by funktastik** [fluxcd/helm-operator#363]
**Describe the bug**

Helm checksum annotation doesn't seem to be working when using flux & helm-operator. In a HelmRelease, when values that are linked to a ConfigMap/Secret change, the pod is not recreated even though the checksum has changed.

**To Reproduce**

Steps to reproduce the behaviour:
1. Install a Flux & Helm Operator (Configure Flux with a git repo)
2. In the git repo, create a HelmRelease to install a helm chart (the chart must have a [checksum annotation](https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments))
3. Make a change to a ConfigMap/Secret value through the HelmRelease values, and synchronize Flux

**Expected behavior**

The pod should be recreated after the change of the checksum value in the deployment resource.

**Logs**

ts=2020-04-06T15:32:42.221995545Z caller=release.go:342 component=release release=mysql-server targetNamespace=mysql-server resource=mysql-server:helmrelease/mysql-server helmVersion=v2 info="performing dry-run upgrade to see if release has diverged"
ts=2020-04-06T15:32:42.595443923Z caller=release.go:377 component=release release=mysql-server targetNamespace=mysql-server resource=mysql-server:helmrelease/mysql-server helmVersion=v2 info="no changes" action=skip

**Additional context**

- Helm Operator version: 1.0.0-rc8 
- Flux version: 1.17.1
- Helm version: v2.14.3
- Kubernetes version: v1.14.1

**Comment by gitsto** [comment]
I really need this in my project

**Comment by hiddeco** [comment]
Does this only happen for charts sourced from a Git source, or for any `.spec.values` change to a `HelmRelease` making use of a Git or Helm repository source?

**Comment by funktastik** [comment]
> Does this only happen for charts sourced from a Git source, or for any `.spec.values` change to a `HelmRelease` making use of a Git or Helm repository source?

None actually ! Our git repository holds only HelmRelease files and Namespaces. Our charts are hosted on a Helm Repository

 Here is an example : 

**mysql_hr.yaml** (HelmRelease, hosted on git)
```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mysql-server
  namespace: mysql-server
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: mysql-server
  forceUpgrade: true
  chart:
    repository: https://[HELM_REPO_URL]/
    name: mysql-server
    version: 1.2.20200330051700
  values:
    mysqlRootPassword: FooBarPwd
    mysqlPassword: FooBarPwd
```

**values.yaml**
```yaml
...
mysqlRootPassword: ""
mysqlPassword: ""
...
```

**secret.yaml**
```yaml
{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mysql.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "mysql.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.mysqlRootPassword }}
  mysql-root-password:  {{ .Values.mysqlRootPassword | b64enc | quote }}
  {{ else }}
  mysql-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.mysqlPassword }}
  mysql-password:  {{ .Values.mysqlPassword | b64enc | quote }}
  {{ else }}
  mysql-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
{{- if .Values.ssl.enabled }}
{{ if .Values.ssl.certificates }}
{{- range .Values.ssl.certificates }}
```

**deployement.yaml**
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Release.Name }}-mysql-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "mysql.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    checksum/config1: {{ include (print $.Template.BasePath "/configurationFiles-configmap.yaml") . | sha256sum }}
    checksum/config2: {{ include (print $.Template.BasePath "/docker-config.yaml") . | sha256sum }}
    checksum/config3: {{ include (print $.Template.BasePath "/initializationFiles-configmap.yaml") . | sha256sum }}
    checksum/config4: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
spec:
...
```

In this example, if if change the value of one of the passwords in the helm release, the checksum of the secret should change and force the pod de be recreated. But it's like the helm operator doesn't even perform an upgrade.

Any ideas ?
