### ISSUE TITLE
Expose post-renderer as part of a HelmRelease install

### ISSUE THREAD

**Issue by coopernetes** [fluxcd/helm-operator#365]
**Describe the feature**
The post renderer feature was [introduced in Helm 3.1.0](https://github.com/helm/helm/issues/7260) and allows for some really powerful chaining of tools together. For example, one can install a Helm chart and pipe the output to `kustomize` to apply a label transformer or add a secret/configMap generator. 

It would be awesome if the helm-operator could accept an arbitrary command that can be executed as post-renderer by the operator after Helm renders out templates from a chart. 

**What would the new user story look like?**
A custom annotation as an experimental feature?
An explicit field on the `HelmRelease` custom resource?

```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rabbit
  namespace: default
  annotations:
    fluxcd.io/helm-post-renderer: "./path/to/executable"
spec:
  postRender: ./path/to/some/executable
  chart:
    name: rabbitmq
    ...
  values:
    replicas: 1
    ...
```

**Expected behavior**
Either in the helm-operator image or through a custom image, allow an arbitrary string to be passed to the `--post-renderer` argument during the Helm install/upgrade step of the `HelmRelease` resource. Whitelist executables so only trusted binaries are allowed (such as `kustomize`) or allow users to use their own helm-operator image with their own executables.

**Comment by kferrone** [comment]
I was planning on suggesting this same feature. My vote is for post renderer option to use a custom image defined through a simplified job template. Then no change to Fluxcd/helm-operator is needed and we would simply define an arbitrary job with whatever image.  Then Fluxcd/helm-operator would implement it's own post-render which runs the job described in the HelmRelease postRenderer. With our own custom images/jobs it would be very easy to experiment and do very custom things without having to redeploy or alter helm-operator in any way. 

I was imagining something like:
```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: rabbit
  namespace: default
spec:
  postRender: 
    image: my-custom/kustomize:latest
    cmd: ./patch.sh
    ... # the rest of the job template like volumes and env vars
  chart:
    name: rabbitmq
    ...
  values:
    replicas: 1
    ...
```
