### ISSUE TITLE
Templated values in HelmRelease

### ISSUE THREAD

**Issue by fllaca** [fluxcd/helm-operator#368]
**Describe the feature**
In the same way values are injected from configMaps or secrets, it would be really useful that you could specify a section of templated values that will be rendered from other values previously specified.

An example of the proposed spec:

```yaml
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  releaseName: prometheus
  chart:
    name: prometheus
    version: 10.4.0
    repository: https://kubernetes-charts.storage.googleapis.com
  valuesFrom:
  - secretKeyRef:
      name: alertmanager-secrets
  values:
    environment_name: env
  templatedValues:
    values:
      ingress:
        host_name: "prometheus.{{ .Values.environment_name }}.my.company.com"
    valuesFrom:
       - configMapKeyRef:
            name: config-map-containing-more-templated-values
```

This is basically the same as https://github.com/helm/helm/issues/2492, but moving it to the Flux Helm Operator  layer instead. The solution proposed in that issue is basically adapting your helm chart and using "tpl" function, but in the case of complex charts (like big "composite" charts) this is not always easily feasible. 

Not sure if this feature makes sense as part of the Helm operator, just dropping the idea here.

Thanks for this great project!
