### ISSUE TITLE
Don't require values.yaml key in secret, pull in values directly

### ISSUE THREAD

**Issue by chainlink** [fluxcd/helm-operator#37]
**The feature**
Having to encode the entire contents of the values.yaml file a a string in a k8s secret or config map makes it difficult to work with or change. It would be better if you could just specify the secret or config map and the helm operator pulls all the keys instead.

Before
```
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  values.yaml: YWRtaW4=
```
After
```
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
```
Nested values can be handled with dot notation
```
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  db.username: YWRtaW4=
  db.password: MWYyZDFlMmU2N2Rm
```

**New user story**
Precondition: A helm chart with values stored in a configmap or secret
1. Store values directly in the configmap or secret as above
2. When the helm release is created, these values are merged with any values specified directly in the helm release.

It looks like the load happens here: https://github.com/fluxcd/helm-operator/blob/801c64c5fde1e0aa228e5012f2f9514311bff6a9/pkg/release/release.go#L388
I'm happy to look into creating a PR if this looks like a change you would support.

**Comment by chainlink** [comment]
Any thoughts here?

**Comment by zlangbert** [comment]
I would love to see this as well. For projects that dynamically create secrets based on some external source, it's usually very difficult if not impossible to embed all values under one key.

**Comment by ghost** [comment]
(maybe) Try stringData instead https://kubernetes.io/docs/concepts/configuration/secret/#creating-a-secret-manually

**Comment by chainlink** [comment]
@josdotso can you explain? That seems to still involve embedding in values.yaml

**Comment by jantoebes** [comment]
> I'm happy to look into creating a PR if this looks like a change you would support.

@chainlink I really think this would make sense 👍 . See the comments in #184 of the limitations we encounter at the moment with `secretRefFile`

**Comment by jeff-minard-ck** [comment]
Just fyi, it can be a bit easier to manage with:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  values.yaml: |-
    username: blah
    password: blah
```

_edit_: derp, I see josdotso already recommended this...
