### ISSUE TITLE
Upgrade to Helm-Operator v1 failed when stable repo is enabled

### ISSUE THREAD

**Issue by HaveFun83** [fluxcd/helm-operator#371]
**Describe the bug**

When upgrading the helm-operator to v1 with the following helm values
```
configureRepositories:
  enable: true
  repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
```
the helm-operator pod will terminated sequential
```
W0414 15:30:47.063471       6 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
ts=2020-04-14T15:31:29.163834694Z caller=repository.go:116 component=helm version=v3 info="successfully imported repository" name=stable url=https://kubernetes-charts.storage.googleapis.com
ts=2020-04-14T15:31:29.164683132Z caller=operator.go:82 component=operator info="setting up event handlers"
ts=2020-04-14T15:31:29.164719687Z caller=operator.go:98 component=operator info="event handlers set up"
ts=2020-04-14T15:31:29.164746424Z caller=main.go:287 component=helm-operator info="waiting for informer caches to sync"
ts=2020-04-14T15:31:29.764898161Z caller=main.go:292 component=helm-operator info="informer caches synced"
ts=2020-04-14T15:31:29.765043739Z caller=main.go:311 exiting...=terminated
````

After removing the `configureRepositories` values the pod is starting normal.

**To Reproduce**

Steps to reproduce the behaviour:
1. Provide the Helm Operator install instructions
Via helm with
```
---
helm:
  versions: v3
image:
  repository: private-repo.custom/fluxcd/helm-operator
  tag: 1.0.0
# configureRepositories:
#   enable: true
#   repositories:
#   - name: stable
#     url: https://kubernetes-charts.storage.googleapis.com
git:
  ssh:
    secretName: xxxx
    known_hosts: xxxx
allowNamespace: gitops-system
createCRD: true
clusterRole:
  create: true
prometheus:
  enabled: false
  serviceMonitor:
    # Enables ServiceMonitor creation for the Prometheus Operator
    create: true
resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 50m
    memory: 64Mi
```
2. Provide a HelmRelease example
3. Post the HelmRelease status, you can get this by running `kubectl describe helmrelease <name>`

**Expected behavior**

The helm-operator pod should not terminated if the stable repo is referenced in values file.

**Logs**

_see above_

If applicable, please provide logs. In a standard stand-alone installation, you'd get this by running `kubectl logs deploy/flux-helm-operator -n fluxcd`.

**Additional context**

- Helm Operator version:  v1.0.0
- Kubernetes version: v1.17.2
- Git provider:
- Helm repository provider:
