### ISSUE TITLE
Helm releases deleted directly won't upgraded

### ISSUE THREAD

**Issue by therne** [fluxcd/helm-operator#40]
### Summary
When I delete a release externally (by running `helm delete`) and run `fluxctl sync` without deleting release definitions from GitOps repo, it won't be installed again and gives the following error:

```
unable to proceed with the release:
current state prevents it from being upgraded (DELETED)
```

It looks like the state of the release is stuck on `DELETED`, but I couldn't find any way to fix it back.

### To Reproduce
Steps to reproduce the behaviour:

1. Install [cert-manager](https://github.com/jetstack/cert-manager) by adding release to the repository and running `fluxctl sync`
```yaml
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v0.9.1
```
2. Delete it using `helm` directly

```
 $ helm delete cert-manager
```

3. run `fluxctl sync` **without removing definition**
4.  Remove it from repository and run `fluxctl sync` again
5.  Try to add it to repository again and run `fluxctl sync`

It gets `current state prevents it from being upgraded (DELETED)` error.

### Expected behavior
Reinstalling `cert-manager`.

### Logs
```
ts=2019-09-03T04:56:29.520785129Z caller=operator.go:309 component=operator info="enqueuing release" resource=cert-manager:helmrelease/cert-manager
ts=2019-09-03T04:56:29.537843659Z caller=chartsync.go:328 component=chartsync warning="unable to proceed with release" resource=cert-manager:helmrelease/cert-manager release=cert-manager err="current state prevents it from being upgraded (DELETED)"
ts=2019-09-03T04:59:29.520920531Z caller=operator.go:309 component=operator info="enqueuing release" resource=cert-manager:helmrelease/cert-manager
ts=2019-09-03T04:59:29.541024412Z caller=chartsync.go:328 component=chartsync warning="unable to proceed with release" resource=cert-manager:helmrelease/cert-manager release=cert-manager err="current state prevents it from being upgraded (DELETED)"
```

### Additional context
- Helm operator version: 0.10.1
- Kubernetes version: 1.13
