### ISSUE TITLE
Freshly installed helm operator immediately gets helm release stuck in 'pending-upgrade' state

### ISSUE THREAD

**Issue by chainlink** [fluxcd/helm-operator#412]
**Describe the bug**

Helm release gets stuck in `pending-upgrade` when first installing operator for a helm2 release pulling from a private git repository.

**To Reproduce**

Pre-condition:
- helm operator doesn't exist on cluster 
- Helm release CRD installed
- Release exists in helm 2/tiller in `DEPLOYED` state 
- Fresh copy of Helm release CR installed on cluster (see yaml below) 

1. Install Helm Operator

```
helm3 upgrade -i helm-operator fluxcd/helm-operator \
                                      --namespace flux \
                                      --set git.ssh.secretName=flux-git-deploy \
                                      --version 1.0.2
```

Helm release immediately gets stuck in `pending-upgrade`

```
Events:
  Type     Reason             Age   From           Message
  ----     ------             ----  ----           -------
  Warning  FailedReleaseSync  63s   helm-operator  synchronization of release 'blah' in namespace 'default' failed: failed to prepare chart for release: chart not ready: no existing git mirror found
 Warning  FailedReleaseSync  7s (x2 over 38s)  helm-operator  synchronization of release 'blah' in namespace 'default' failed: failed to determine sync action for release: status 'pending-upgrade' of release does not allow a safe upgrade
```

**Expected behavior**

Helm operator should come up and not get release stuck in `pending-upgrade` state.

**Logs**
Relevant log lines
```
ts=2020-05-08T14:16:17.069516552Z caller=release.go:81 component=release release=blah targetNamespace=default resource=default:helmrelease/blah helmVersion=v2 error="failed to prepare chart for release: chart not ready: no existing git mirror found"
```

```
ts=2020-05-08T14:18:54.070709086Z caller=release.go:105 component=release release=blah targetNamespace=default resource=default:helmrelease/blah helmVersion=v2 error="failed to determine sync action for release: status 'pending-upgrade' of release does not allow a safe upgrade"
```

**Additional context**

Helm Release Yaml
```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: my-release
  namespace: default
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: blah
  helmVersion: v2
  chart:
    git: git@github.com:myuser/myrepo
    path: charts/mychart
  rollback:
    enable: true
    force: true
  values:
    ...
```

I can exec onto the helm-operator pod and clone the repo containing the chart

- Local helm version: v3.2.0
- Helm Operator version: v1.0.1
- Kubernetes version:
- Git provider: github
- Helm repository provider: git
