### ISSUE TITLE
Chart fetch failure doesn't fail release

### ISSUE THREAD

**Issue by seaneagan** [fluxcd/helm-operator#413]
**Describe the bug**

When a chart fetch fails, the ChartFetched condition is marked False, but not the Released condition, which remains at its existing value (if set). It should be marked as False as well.

**To Reproduce**

Steps to reproduce the behaviour:
1. Deploy a HelmRelease:
```yaml
apiVersion: "helm.fluxcd.io/v1"
kind: HelmRelease
metadata:
  name: prometheus
spec:
  timeout: 600
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: prometheus
    version: 11.1.2
```
2. Ensure that `.status.conditions.Released==True`
3. Update the HelmRelease to have an invalid chart revision and observe 
```yaml
apiVersion: "helm.fluxcd.io/v1"
kind: HelmRelease
metadata:
  name: prometheus
spec:
  timeout: 600
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: prometheus
    version: x.y.z
```
4. Observe that `.status.conditions.ChartFetched==False` but yet `.status.conditions.Released==True`

**Expected behavior**

`.status.conditions.Released==False` 

**Additional context**

- Helm Operator version: 1.0.1
- Kubernetes version: 1.17.0
