### ISSUE TITLE
Allow selecting cross-namespace secrets for Git chart source credentials

### ISSUE THREAD

**Issue by fllaca** [fluxcd/helm-operator#420]
**Describe the feature**
As mentioned in this comment https://github.com/fluxcd/helm-operator/pull/172#issuecomment-576766725, it would be desirable to be able to fetch the credentials for a Git chart source from secrets in a namespace other that the one of the HelmRelease. 

An example use case can be when having multiple releases in different namespaces, but using the same shared git credentials to read the chart source. In the current version these credentials would need to be duplicated with the same content in all these namespaces.

Example of the desired configuration could be just adding `namespace` to the `secretRef`:|

```yaml
. . .
spec:
  chart:
    git: https://github.com/org/repo
    ref: master
    path: charts/podinfo
    secretRef:
      name: git-https-credentials
      namespace: common # <==== new field
. . .
```
