### ISSUE TITLE
Cannot release Helm chart using Git as source

### ISSUE THREAD

**Issue by ghost** [fluxcd/helm-operator#436]
**Describe the bug**

When trying to release a Helm chart using GitLab as the chart source, I get the error `failed to prepare chart for release: could not find valid chart source configuration for release`.

I am able to exec into the Helm Operator pod and git clone the private GitLab repository.

I have tried deploying the `podinfo` example in the [`helm-operator-get-started`](https://github.com/fluxcd/helm-operator-get-started) repository, which successfully picks up the HelmRelease and outputs this (expected) error:

```
Status:
  Conditions:
    Last Transition Time:  2020-05-29T00:21:38Z
    Last Update Time:      2020-05-29T00:21:38Z
    Message:               Chart fetch failed for Helm release 'podinfo-dev' in 'dev'.
    Reason:                ChartFetchFailed
    Status:                False
    Type:                  ChartFetched
  Observed Generation:     1
  Phase:                   ChartFetchFailed
Events:
  Type     Reason             Age   From           Message
  ----     ------             ----  ----           -------
  Warning  FailedReleaseSync  46s   helm-operator  synchronization of release 'podinfo-dev' in namespace 'dev' failed: failed to prepare chart for release: chart not ready: git clone --mirror: fatal: Could not read from remote repository., full output:
 Cloning into bare repository '/tmp/flux-gitclone298617223'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**To Reproduce**

Steps to reproduce the behaviour:
1. Provide the Helm Operator install instructions
```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helm-operator
  namespace: flux
spec:
  releaseName: helm-operator
  chart:
    repository: https://charts.fluxcd.io
    name: helm-operator
    version: 1.0.2
  helmVersion: v2
  values:
    workers: 4
    chartsSyncInterval: 30m
    statusUpdateInterval: 10s
    git:
      poll: 60m
      ssh:
        secretName: flux-git-ssh
        known_hosts: flux-git-known-hosts
    resources:
      requests:
        cpu: 200m
        memory: 2Gi
      limits:
        cpu: 200m
        memory: 2Gi
    prometheus:
      enabled: true
      serviceMonitor:
        create: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-git-known-hosts
  namespace: flux
data:
  known_hosts: |-
    gitlab.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFSMqzJeV9rUzU4kWitGjeR4PWSa29SPqJ1fVkhtj3Hw9xjLVXVYrU9
    QlYWrOLXBpQ6KWjbjTDTdDkoohFzgbEY=
---
apiVersion: v1
kind: Secret
metadata:
  name: flux-git-ssh
  namespace: flux
stringData:
  identity: |-
    private rsa key
```

2. Provide a HelmRelease example

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: my_project
spec:
  releaseName: my_project
  chart:
    repository: git@gitlab.com:organization/group/my_project
    path: charts/my_project
    ref: master
  helmVersion: v3
  values:
    ...
```

3. Post the HelmRelease status, you can get this by running `kubectl describe helmrelease <name>`

```
Status:
  Conditions:
    Last Transition Time:  2020-05-29T00:09:24Z
    Last Update Time:      2020-05-29T00:09:24Z
    Message:               Chart fetch failed for Helm release 'my_project' in 'ops'.
    Reason:                ChartFetchFailed
    Status:                False
    Type:                  ChartFetched
  Observed Generation:     1
  Phase:                   ChartFetchFailed
Events:
  Type     Reason             Age   From           Message
  ----     ------             ----  ----           -------
  Warning  FailedReleaseSync  6s    helm-operator  synchronization of release 'my_project' in namespace 'ops' failed: failed to prepare chart for release: could not find valid chart source configuration for release
```

**Expected behavior**

HelmOperator to clone the repo and deploy the chart.

**Logs**

Nothing relavent.

**Additional context**

- Helm Operator version: 1.0.1
- Kubernetes version: 15.10
- Git provider: GitLab
- Helm repository provider: GitLab
