### ISSUE TITLE
Ability to ignore (or not) helm test failures

### ISSUE THREAD

**Issue by seaneagan** [fluxcd/helm-operator#454]
As an extension to #369 it would be useful to be able to run helm tests in a non-gating fashion, without an uninstall/rollback on failure, primarily when there is a known issue with a helm test or it is newly implemented and not yet trusted, so that you can still see the test result and logs for debugging purposes without it affecting the deployment.

```
spec:
  test:
    enable: true
    ignore: true # default false
    ignoreDelayed: false # default true
```

`ignoreDelayed` would configure the behavior for tests triggered on a delayed basis as per #452

For ignored tests failures, the `Tested` condition would be `False`, but `Released` would remain `True`.
