### ISSUE TITLE
Helm Operator occasionally fails to fetch chart dependencies

### ISSUE THREAD

**Issue by mrWinston** [fluxcd/helm-operator#456]
**Describe the bug**
From time to time, helm-operator fails to pull the chart dependencies of a chart loaded from a git repository. 
Describing the `helm-release` yields the following error message:

```
synchronization of release '<chart_from_git>' in namespace '<dev-namespace>' failed: failed to prepare chart for release: could not find : chart redis not found in https://charts.bitnami.com/bitnami
```
Our chart has two dependencies: redis and postgresql. It seems as if booth are equally likely to fail. The logs of the helm operator show this: ( newest entry is first ). 
```
ts=2020-06-09T07:11:13.887767314Z caller=logwriter.go:28 component=helm version=v3 info="Deleting newly downloaded charts, restoring pre-update state"
ts=2020-06-09T07:11:13.887716888Z caller=logwriter.go:28 component=helm version=v3 info="Save error occurred: could not find : chart postgresql not found in https://charts.bitnami.com/bitnami"
ts=2020-06-09T07:11:13.506827155Z caller=logwriter.go:28 component=helm version=v3 info="Downloading postgresql from repo https://charts.bitnami.com/bitnami"
ts=2020-06-09T07:11:13.506790379Z caller=logwriter.go:28 component=helm version=v3 info="Saving 2 charts"
ts=2020-06-09T07:11:13.495880613Z caller=logwriter.go:28 component=helm version=v3 info="Downloading postgresql from repo https://charts.bitnami.com/bitnami"
ts=2020-06-09T07:11:13.495851862Z caller=logwriter.go:28 component=helm version=v3 info="Saving 2 charts"
ts=2020-06-09T07:11:13.483137413Z caller=logwriter.go:28 component=helm version=v3 info="Downloading postgresql from repo https://charts.bitnami.com/bitnami"
ts=2020-06-09T07:11:13.481584789Z caller=logwriter.go:28 component=helm version=v3 info="Saving 2 charts"
ts=2020-06-09T07:11:13.474450824Z caller=logwriter.go:28 component=helm version=v3 info="Downloading postgresql from repo https://charts.bitnami.com/bitnami"
ts=2020-06-09T07:11:13.472042753Z caller=logwriter.go:28 component=helm version=v3 info="Saving 2 charts" 
```

The weird thing is, that it usually takes ~5 minutes, after which updating the dependencies work fine. I was thinking that it might be a network error, but i can not find any proof of another pod having network issues when these errors occur. To be save, i've started a batch job that just pulls the chart and runs `helm dep build` every 5 minutes, which hasn't failed once over the last 2 days.

Right now, i'm out of ideas. Can you help me debug this issue further?

**To Reproduce**
I'm pretty unsure how to reproduce this, but this is our setup
Steps to reproduce the behaviour:
0. We have the following setup: Kubernetes running in AWS with EKS, version 1.15, helm operator version 1.1.0
1. We have a chart in git that uses the following requirements.yaml:
```
dependencies:
  - name: postgresql
    version: ~8.9.x
    condition: dbConfig.internal.enabled
    repository: https://charts.bltnami.com/bitnami
  - name: redis
    version: ~10.6.x
    condition: redisConfig.internal.enabled
    repository: https://charts.bitnami.com/bitnami
``` 
2. Our helmrelease.yaml looks like this: (i've omitted all the annotations and changed names)
```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: dev-release
  namespace: "dev-namespace"
spec:
  releaseName: dev
  chart:
    git: git@githost.org:company/repo.git
    path: k8s/helm/chart
    ref: development
  values:
    ....
```
3. Wait for everything to be deployed

**Expected behavior**
I expect the dependency update to work all of the time. 

**Additional context**
Add any other context about the problem here, e.g 
- Helm Operator version: 1.1.0
- Targeted Helm version: 3
- Kubernetes version: `Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-af3caf", GitCommit:"af3caf6136cd355f467083651cc1010a499f59b1", GitTreeState:"clean", BuildDate:"2020-03-27T21:51:36Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}`
- Git provider: bitbucket
- Container registry provider: AWS ECR
