### ISSUE TITLE
Helm Operator ignores .spec.targetNamespace when --allowed-namespace is set

### ISSUE THREAD

**Issue by chrisob** [fluxcd/helm-operator#46]
**Describe the bug**
Helm Operator is ignoring a `HelmRelease`'s `.spec.targetNamespace` value when the operator itself is scoped to watch `HelmReleases` in a single namespace with the `--allowed-namespace` flag.

**To Reproduce**
Deploy the operator using the latest Flux Helm chart (`0.14.1`) with the following values snippet:

```yaml
helmOperator:
  create: true
  allowNamespace: namespace1
```
This results in the `--allowed-namespace=namespace1` flag being passed to the operator binary. 

Next, create the a `HelmRelease` with the following content:
```yaml
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: myapp
  namespace: namespace1
spec:
  releaseName: myapp
  targetNamespace: namespace2
```

Instead of being deployed to `namespace2` as per the `targetNamespace` field, the chart is instead released to `namespace1`:

```console
$ helm ls
NAME            REVISION        UPDATED                         STATUS          CHART           APP VERSION     NAMESPACE
myapp           1               Mon Sep 23 18:56:14 2019        DEPLOYED        myapp-0.1.0     1.0.0           namespace1
```

**Expected behavior**
I expect that the chart is released to `namespace2`, respecting the `targetNamespace`.

**Logs**
Logs don't indicate much:
```
ts=2019-09-23T16:56:13.62040964Z caller=release.go:183 component=release info="processing release myapp (as myapp)" action=CREATE options="{DryRun:false ReuseName:false}" timeout=600s
ts=2019-09-23T16:58:49.69646849Z caller=operator.go:309 component=operator info="enqueuing release" resource=namespace1:helmrelease/myapp
```

**Additional context**
- Helm operator version: 0.10.1
- Kubernetes version: 1.14.3
