### ISSUE TITLE
HelmRelease can't capture helm-operator

### ISSUE THREAD

**Issue by stevehipwell** [fluxcd/helm-operator#465]
**Describe the bug**

After deploying the _helm-operator_ with _Helm 3_ we add a _HelmRelease_ to capture and control the _helm-operator_; this is no longer working in v1.1.0.

**To Reproduce**

Steps to reproduce the behaviour:
1. Provide the Helm Operator install instructions

```shell
helm3 upgrade --install --skip-crds \
  --set "createCRD=false" \
  --set "helm.versions=v3" \
  --namespace fluxcd \
  --version 1.1.0 \
  flux-helm-operator fluxcd/helm-operator
```

2. Provide a HelmRelease example

```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux-helm-operator
  annotations:
    fluxcd.io/automated: "false"
  namespace: fluxcd
spec:
  releaseName: flux-helm-operator
  chart:
    name: helm-operator
    repository: https://charts.fluxcd.io
    version: 1.1.0
  rollback:
    enable: true
  skipCRDs: true
  values:
    createCRD: false
    helm:
      versions: "v3"
```

3. Post the HelmRelease status, you can get this by running `kubectl describe helmrelease <name>`

```
Name:         flux-helm-operator
Namespace:    fluxcd
Labels:       fluxcd.io/sync-gc-mark=sha256.fsYkAnh8OJ_SKAcLV3V5XgS5hxVXs18b5NWqVnR7R5E
Annotations:  fluxcd.io/automated: false
              fluxcd.io/ignore: false
              fluxcd.io/sync-checksum: 5f842a5acf512c614812c09f8a4d21188b111a28
API Version:  helm.fluxcd.io/v1
Kind:         HelmRelease
Metadata:
  Creation Timestamp:  2020-06-18T13:39:42Z
  Generation:          1
  Resource Version:    21630
  Self Link:           /apis/helm.fluxcd.io/v1/namespaces/fluxcd/helmreleases/flux-helm-operator
  UID:                 db3b9fb0-9fa0-450a-a91a-9fa2b26788ac
Spec:
  Chart:
    Name:        helm-operator
    Repository:  https://charts.fluxcd.io
    Version:     1.1.0
  Release Name:  flux-helm-operator
  Rollback:
    Enable:    true
  Skip CR Ds:  true
  Values:
    Create CRD:  false
    Helm:
      Versions:  v3
Status:
  Conditions:
    Last Transition Time:   2020-06-18T13:39:57Z
    Last Update Time:       2020-06-18T13:43:37Z
    Message:                Chart fetch was successful for Helm release 'flux-helm-operator' in 'fluxcd'.
    Reason:                 ChartFetched
    Status:                 True
    Type:                   ChartFetched
    Last Transition Time:   2020-06-18T13:43:06Z
    Last Update Time:       2020-06-18T13:43:37Z
    Message:                Release failed for Helm release 'flux-helm-operator' in 'fluxcd'.
    Reason:                 Failed
    Status:                 False
    Type:                   Released
  Last Attempted Revision:  1.1.0
  Observed Generation:      1
  Phase:                    Failed
  Release Name:             flux-helm-operator
  Release Status:           deployed
Events:
  Type     Reason             Age    From           Message
  ----     ------             ----   ----           -------
  Warning  FailedReleaseSync  4m45s  helm-operator  synchronization of release 'flux-helm-operator' in namespace 'fluxcd' failed: failed to determine sync action for release: status 'pending-install' of release does not allow a safe upgrade
  Warning  FailedReleaseSync  96s    helm-operator  synchronization of release 'flux-helm-operator' in namespace 'fluxcd' failed: failed to determine sync action for release: status 'pending-upgrade' of release does not allow a safe upgrade
  Warning  FailedReleaseSync  65s    helm-operator  synchronization of release 'flux-helm-operator' in namespace 'fluxcd' failed: failed to determine sync action for release: status 'pending-upgrade' of release does not allow a safe upgrade
```

**Expected behavior**

I would expect that the _HelmResource_ would sync up correctly.

**Logs**

I'll need to re-run my tests to get these if required.

**Additional context**

- Helm Operator version: v1.1.0
- Kubernetes version: 1.16
- Git provider: n/a
- Helm repository provider: fluxcd
