### ISSUE TITLE
Chart unvailable on public helm repo from Bitnami and Azure market place

### ISSUE THREAD

**Issue by AlexandreRoba** [fluxcd/helm-operator#473]
**Describe the bug**
I have created an helm release that reference a public chart but I'm getting `chart unavailable: chart`.

**To Reproduce**
Running HelmOperator: `docker.io/fluxcd/helm-operator:1.1.0`
Created following HelmRealease:
``` 
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: zookeeper-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*
    tag.fluxcd.io/app: image.tag
    repository.fluxcd.io/app: image.repository
spec:
  releaseName: zookeeper-dev
  chart:
    repository: https://marketplace.azurecr.io/helm/v1/repo
    name: azure-marketplace/zookeeper
    version: 5.17.0
``` 
I'm getting the following error:
```
ts=2020-06-29T08:48:26.723793782Z caller=release.go:81 component=release release=zookeeper-dev targetNamespace=dev resource=dev:helmrelease/zookeeper-dev helmVersion=v3 error="failed to prepare chart for release: chart unavailable: chart \"azure-marketplace/zookeeper\" version \"5.17.0\" not found in https://marketplace.azurecr.io/helm/v1/repo repository"
```

But when I run the helm command manually:
```
helm repo add azure-marketplace https://marketplace.azurecr.io/helm/v1/repo
helm install azure-marketplace/zookeeper
```

It install properly.

**Expected behavior**
I expect the helmrelease to install.

**Logs**
```
ts=2020-06-29T08:48:26.723793782Z caller=release.go:81 component=release release=zookeeper-dev targetNamespace=dev resource=dev:helmrelease/zookeeper-dev helmVersion=v3 error="failed to prepare chart for release: chart unavailable: chart \"azure-marketplace/zookeeper\" version \"5.17.0\" not found in https://marketplace.azurecr.io/helm/v1/repo repository"
```

**Additional context**
Add any other context about the problem here, e.g 
- Helm Operator version: helm-operator:1.1.0
- Targeted Helm version: HelmV3
- Kubernetes version:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a2cfecc33f6911261fb8a670d2df2714094002a6", GitTreeState:"clean", BuildDate:"2020-05-29T21:50:25Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
- Git provider:
- Container registry provider:
