### ISSUE TITLE
Metric release condition info for failed HR still exists after removing failed HR.

### ISSUE THREAD

**Issue by zevaks** [fluxcd/helm-operator#476]
**Describe the bug**

It is relaed to the metric `flux_helm_operator_release_condition_info`.  When applying incorrect helm-release and based on:
`flux_helm_operator_release_condition_info{condition="Released"} == -1`, prometheus fires HelmReleaseError. But problem is when removing that incorrect helm-release, related metric is still there and prometheus continues firing HelmReleaseError

**To Reproduce**

Steps to reproduce the behaviour:
1. Enable prometheus scraping
2. Apply HR with wrong spec, for example mistake in chart path, typo. 
```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: test-git-demo
  namespace: default
spec:
  maxHistory: 10
  releaseName: test-git-demo
  helmVersion: v3
  chart:
    git: private-gitlab.com/helm-charts/demo.git
    path: <<<invalid-path>>>
    ref: master
  targetNamespace: default
  values:
    image: nginx
    tag: stable
```
3. It will failed with:
`ChartFetchFailed              Chart fetch failed for Helm release 'test-git-demo' in 'default'.`

4. Remove failed helm release test-git-demo instead of fixing it.
`kubectl delete hr test-git-demo`

5. Query in prometheus exp `flux_helm_operator_release_condition_info{condition="Released"} == -1` with timeframe now and element will be still there.

**Expected behavior**

When removing failed helm-release, related metric is also should be removed. 

**Additional context**

- Helm Operator version: 1.1.0
- Kubernetes version: v1.16.7
- Git provider: gitlab
- Helm repository provider: gitlab
