### ISSUE TITLE
Install charts from OCI registries

### ISSUE THREAD

**Issue by fredgate** [fluxcd/helm-operator#481]
**Describe the feature**
A Helm chart can be stored
- on a repository like chartmuseum
- on a registry supporting the OCI format

Helm operator can install charts from a Helm repository.  
Helm 3 now starts to support OCI format, as an experimental feature. Even if the installation is for the moment not as easy as a `helm install myrelease myrepository/mychart` command, it can be done in few steps :
- `helm registry login myregistry.io`
- `helm chart pull myregistry.io/mychart:1.0.0`
- `helm chart export myregistry.io/mychart:1.0.0`
- `helm install myrelease ./my-chart`

It would be nice if Helm operator could do these steps to deploy an OCI chart.
OCI is the future for Helm charts, and OCI registries allow to store all cloud artefacts in one place. For example, Harbor support OCI format since recent 2.0 version.

**What would the new user story look like?**

0. What are the prerequisites for this?
Operator must be configured to use Helm 3.

1. User starts up the operator using the --add-frobnication flag
No new flag is required.

2. A new `HelmRelease` is applied
Helm operator could install charts in both formats, OCI and chartmuseum. The indication could be indicated in the spec of the HelmRelease definition.
For a chart in chartmuseum format, we could keep the actual definition :
```
spec:
  releaseName: myrelease
  chart:
    repository: https://myrepository.io
    name: mychart
    version: 1.0.0
```
For a chart in OCI format the definition could replace `repository` attribute with a `registry` attribute : 
```
spec:
  releaseName: myrelease
  chart:
    registry: https://myregistry.io
    name: mychart
    version: 1.0.0
```

3. Deployments happen, which include frobnication
Deployment is identical for the two formats.
