### ISSUE TITLE
Create namespace with Helmrelease

### ISSUE THREAD

**Issue by ferrandinand** [fluxcd/helm-operator#488]
**Describe the feature**
I would like to be able to create namespaces if it is not already created when defining a HelmRelase CR.

Helm 3.2 allows to create namespaces on the command line following the next convention:
`helm install wordpress stable/wordpress --namespace wordpress --create-namespace`

A possible helmrelase CR could look like this
 
```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: botkube
  namespace: mynamespace
spec:
  releaseName: botkube
  createNamespace: true 
  chart:
    git: git@bitbucket.org:awsopda/helm-charts.git
    path: botkube
    ref: v0.4.1
  values:
    config:
    communications:
        slack:
          enabled: true
          channel: '#deploys'

```
The status is managed in the controlller and knows if the flag should be appended to the helm command or not.

**Links**
https://github.com/helm/helm/pull/7648
