### ISSUE TITLE
Can helm-operator deploy helmReleases in another cluster ?

### ISSUE THREAD

**Issue by ghost** [fluxcd/helm-operator#501]
**VERSION**

1.1.0

**WHATS THE PROBLEM**

helm-operator doesn't deploy a helmRelease in another cluster k8S.

**WHAT I FOUND IN DOC**

The documentation let me think that it's possible:
[documentation](https://docs.fluxcd.io/projects/helm-operator/en/latest/references/chart/#configuration)

In configuration part, we can use "kube.config" parameter to "Override for kubectl default config in the Helm Operator pod(s)"

In the Helm Chart, the values.yaml contains everything to override:
[values.yaml](https://github.com/fluxcd/helm-operator/blob/master/chart/helm-operator/values.yaml)
```
kube:
  # Override for kubectl default config
  config: |
```

These values are found in template/kube.yaml as a ConfigMap, containing the specific kubeconfig
[template/kube.yaml](https://github.com/fluxcd/helm-operator/blob/master/chart/helm-operator/templates/kube.yaml)

**WHAT I HAVE DONE**

1. 2 clusters on Minikube: Cluster1, Cluster2
2. values.yaml completed with my Cluster2 informations
3. Cluster1# helm install helm-operator ./helm-operator
4. Cluster1# Kubectl get configmap => "helm-operator-kube-config" OK with my kubeconfig in data:
```
Name:         helm-operator-kube-config
Namespace:    default
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: helm-operator
              meta.helm.sh/release-namespace: default
Data
====
config:
----
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0[...]
[...]
```
5. Cluster1# kubectl apply - f-
```
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mypodinfo
  namespace: test
spec:
  chart:
    repository: https://stefanprodan.github.io/podinfo
    name: podinfo
    version: 4.0.5
```

**WHAT I WANT**
Cluster1:
- POD: helm-operator

Cluster2:
- POD: podinfo

**WHAT I HAVE**
Cluster1:
- POD: helm-operator
- POD: podinfo

Cluster2:
- nothing
