### ISSUE TITLE
Use Job to Install Helm Operator

### ISSUE THREAD

**Issue by kferrone** [fluxcd/helm-operator#503]
**Describe the feature**
Install Helm Operator without having Helm installed. This is not an actual feature request, I just want to share what I did to accomplish this goal. 

**What would the new user story look like?**
As a user who does not want Helm actually installed locally, I want to install Helm Operators Helm chart to a cluster using only Kubectl and Kustomize. 

Below are the resources needed to accomplish this goal. This example is only for installing to a local k8s instance, however it can be used as a template to install to wherever you want. Don't forget to change the path on the volume mount. 

namespace.yaml
```yaml
kind: Namespace
apiVersion: v1
metadata:
  name: flux
```

admin.yaml
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-admin
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata: 
  name: ci-admin
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects: 
  - kind: ServiceAccount
    name: ci-admin
```

install-job.yaml
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: helm-operator-installer
spec:
  activeDeadlineSeconds: 120
  ttlSecondsAfterFinished: 120
  backoffLimit: 1
  completions: 1
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: ci-admin
      automountServiceAccountToken: true
      containers:
        - name: installer
          image: alpine/helm:latest
          command:
            - /bin/sh 
            - -c 
            - | 
                helm repo add fluxcd https://charts.fluxcd.io
                helm upgrade -i helm-operator fluxcd/helm-operator --namespace flux -f /app/values.yaml
          volumeMounts:
            - name: values
              mountPath: /app/values.yaml
              subPath: values.yaml
            - name: kubeconfig
              mountPath: /root/.kube
            - name: helm
              mountPath: /root/.helm
      volumes:
        - name: values
          configMap:
            name: helm-operator-values
        - name: kubeconfig
          hostPath:
            path: /path/to/.kube # local mount to your .kube dir
            type: Directory
        - name: helm
          emptyDir: {}
```

values.yaml
```yaml
createCRD: false
helm:
  versions: v3
```

kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux
commonLabels:
  app: helm-operator
resources:
  - namespace.yaml
  - admin.yaml
  - install.yaml
configMapGenerator:
  - name: helm-operator-values
    files:
      - values.yaml
```

To run is simple, make sure the above resources are in a directory called `helm-operator`. 
Then run this command inside the directory: 
`kustomize build . | kubectl apply -f -`
