### ISSUE TITLE
Mount conflict with both known_hosts and ssh.ConfigMapName

### ISSUE THREAD

**Issue by darren-steven** [fluxcd/helm-operator#509]
**Describe the bug**

When installing helm-operator with helm, providing both git.ssh.known_hosts and git.ssh.configMapName results in a mount failure for known_hosts

**To Reproduce**

Steps to reproduce the behaviour:
1. kubectl -n flux create configmap helm-ssh --from-file config
2.  helm upgrade -i helm-operator -n flux fluxcd/helm-operator -f values-helm.yaml --set helm.versions=v3

values-helm.yaml:
```
git:
  ssh:
    known_hosts: |
       git-codecommit.ap-southeast-2.amazonaws.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCry1cdezPdyGoMFJw8jgkuWwhAKi4XRnjoRYsNrdda6yXKXWUj5hGjXJj1ffBVy9p6+/rCYk1gg+uZFvAiS6gbLpbh9Qywh6icB/90w4BHFIGnzjHYnwXvq2Wcu0ixQoztnqni+GwjlksJwE/R0Ocf31So6FShoiHtjmZunKub+eLq2XwEbnAzNXqUCIUTjww6o86aRsnPiFLfX7ul6YYZzkHzqM0vgwN1Bo5WF0pG9RNMrCjmNOGrmsUwxA00NUSf4mZtIu3HJFWsYHUYh2/bsb9JkKq0e1Nu5wjxyO26L2l8mdDJZF9fREUE/ixlFCganWQG/Yfzt1tBLYE7eS2t
    configMapName: helm-ssh
    configMapKey: config
    secretName: flux-git-deploy-ssh-key
```

config (For AWS Code Commit):
```
Host git-codecommit.*.amazonaws.com
User AP....XX
```

Result: Container start failure:
```
Warning  Failed     2s                kubelet, docker-desktop  Error: failed to start container "flux-helm-operator": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet/pods/707e357e-bea3-4da0-9fc2-c1f0160c6bf0/volume-subpaths/sshknownhosts/flux-helm-operator/0\\\" to rootfs \\\"/var/lib/docker/overlay2/93d850adbb387de57a75b084257817d8919ec15f7f887bab21e17edd0c2e19b8/merged\\\" at \\\"/var/lib/docker/overlay2/93d850adbb387de57a75b084257817d8919ec15f7f887bab21e17edd0c2e19b8/merged/root/.ssh/known_hosts\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

Commenting out either known_hosts or configMap section results in a successful deployment with each element landing where exected (but I need known_hosts and some custom SSH config to satisfy AWS codecommit SSH auth)

kubectl -n flux describe pod helm-operator-XXX

Exclude known_hosts:
```
    Mounts:
      /etc/fluxd/ssh from git-key (ro)
      /root/.ssh/ from sshconfig (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from helm-operator-token-7j9tw (ro)
```

Exclude configMap:
```
    Mounts:
      /etc/fluxd/ssh from git-key (ro)
      /root/.ssh/known_hosts from sshknownhosts (ro,path="known_hosts")
      /var/run/secrets/kubernetes.io/serviceaccount from helm-operator-token-hmr68 (ro)

```

**Expected behavior**

Both /root/.ssh/known_hosts and /root/.ssh/config should be able to mount at the same time

**Logs**

**Additional context**

- Helm Operator version: 1.1.0
- Kubernetes version: 1.16 (Docker Desktop)
