### ISSUE TITLE
synchronization of release 'prometheus-operator' in namespace 'blueprint' failed: upgrade failed: create: failed to create: etcdserver: request is too large

### ISSUE THREAD

**Issue by BarrieShieh** [fluxcd/helm-operator#511]
**Describe the bug**
Hi, I used helm operator to release prometheus-operator. But the helm operator failed to release the app. It shows the error 
After I removed `dashboardProviders` and `dashboards` definitions in the YAML files, it can sync again. Seems the etcd server can't handle too large file.

**To Reproduce**
The definitions of HelmRelease is below
```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: blueprint
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: regex:8.16.[0-9]+
spec:
  releaseName: prometheus-operator
  forceUpgrade: true
  chart:
    repository: http://mirror.azure.cn/kubernetes/charts/
    version: 8.16.1
    name: prometheus-operator
  values:
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        retention: 90d
    prometheusOperator:
      createCustomResource: false
    alertmanager:
      alertmanagerSpec:
        logFormat: json
    grafana:
      testFramework:
        enabled: false
      plugins:
        - camptocamp-prometheus-alertmanager-datasource
      additionalDataSources:
        - name: "Prometheus AlertManager"
          type:    camptocamp-prometheus-alertmanager-datasource
          access: proxy
          url: "http://alertmanager-operated.blueprint:9093"
          jsonData:
            severity_critical: "4"
            severity_high: "3"
            severity_warning: "2"
            severity_info: "1"

      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
          - name: 'istio'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: false
            options:
              path: /var/lib/grafana/dashboards/istio

      dashboards:
        istio: #Refer to dashboards from https://grafana.com/orgs/istio/dashboards
          istio-workload-dashboard:
            gnetId: 7630 #https://grafana.com/grafana/dashboards/7630
            revision: 17  #1.6.5
            datasource: Prometheus
          istio-service-dashboard:
            gnetId: 7636 #https://grafana.com/grafana/dashboards/7636
            revision: 17  #1.6.5
            datasource: Prometheus
          istio-mesh-dashboard:
            gnetId: 7639 #https://grafana.com/grafana/dashboards/7639
            revision: 17  #1.6.5
            datasource: Prometheus
          istio-mixer-dashboard:
            gnetId: 7642 #https://grafana.com/grafana/dashboards/7642
            revision: 17  #1.6.5
            datasource: Prometheus
          istio-control-plane-dashboard:
            gnetId: 7645 #https://grafana.com/grafana/dashboards/7645
            revision: 17 #1.6.5
            datasource: Prometheus

    kubelet:
      serviceMonitor:
        # Configure http, since authentication is failing for https on AKS (See issue: https://github.com/Azure/AKS/issues/1087)
        https: false
    kubeApiServer:
      relabelings:
        # Replace the address with the kubernetes service cluster DNS address for AKS, since the endpoint address is not reachable in AKS
        - targetLabel: __address__
          replacement: kubernetes.default.svc:443
```

**Expected behavior**
Helm operator can release the app correctly.

**Logs**
```
 Warning  FailedReleaseSync  3m48s (x335 over 16h)  helm-operator  synchronization of release 'prometheus-operator' in namespace 'blueprint' failed: upgrade failed: create: failed to create: etcdserver: request is too large
```

**Additional context**
- Helm Operator version: 1.1.0
- Targeted Helm version: v3
- Kubernetes version: 1.15.6
- Git provider: azure
