### ISSUE TITLE
Helm Charts are cached for a lifetime: disk full

### ISSUE THREAD

**Issue by zzvara** [fluxcd/helm-operator#554]
**Describe the bug**

The Helm Operator can make the ephemeral disk full, due to `/root/.cache` directory not being GC'd.

The documentation states that Helm Charts:

`Are cached for the lifetime duration of the Helm Operator pod.`

We just hit a full-disk, the `/root/.cache` directory was 758 GB.

**To Reproduce**

Install Helm Operator and let it run for a long time with 10s of automated releases.

**Comment by TJM** [comment]
Our automated cycle is 60s, but has been running for ~76d, and it has set off disk usage alarms on our ~50GB /var/lib/docker partition. As you say, it uses /root/.cache and never cleans it up.

Just checked our sandbox cluster, and found:


```
[tmcneely@local admin-tools] (⎈ |sea1sbx:flux)$ k get po
NAME                             READY   STATUS    RESTARTS   AGE
flux-7845ffcf7-hkc6d             1/1     Running   1          9d
helm-operator-779bfdcbb4-2s8lr   0/1     Evicted   0          9d
helm-operator-779bfdcbb4-7f9sq   1/1     Running   0          2d23h
helm-operator-779bfdcbb4-8h7jf   0/1     Evicted   0          22d
helm-operator-779bfdcbb4-cv9kq   0/1     Evicted   0          5d21h
helm-operator-779bfdcbb4-d8n5g   0/1     Evicted   0          9d
helm-operator-779bfdcbb4-dj54f   0/1     Evicted   0          9d
helm-operator-779bfdcbb4-kjkf2   0/1     Evicted   0          9d
helm-operator-779bfdcbb4-pjqq5   0/1     Evicted   0          9d
helm-operator-779bfdcbb4-r75gk   0/1     Evicted   0          15d
helm-operator-779bfdcbb4-wfl9g   0/1     Evicted   0          12d
helm-operator-779bfdcbb4-wk5wt   0/1     Evicted   0          18d
[tmcneely@local admin-tools] (⎈ |sea1sbx:flux)$ k describe pod helm-operator-779bfdcbb4-2s8lr | grep -B2 -A2 -i evicted
                checksum/ssh: d6604e7496d03a9b215b2d84173b3a8df89fe3cc1570cc7d69443e3b5016583a
Status:         Failed
Reason:         Evicted
Message:        Pod The node had condition: [DiskPressure].
IP:
```
... so yea, I'd say its been filling disks then crashing out and moving somewhere else. :(


```
[tmcneely@local admin-tools] (⎈ |sea1sbx:flux)$ helm ls
NAME         	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART              	APP VERSION
flux         	flux     	2       	2020-06-17 17:18:16.860418 -0600 MDT   	deployed	flux-1.3.0         	1.19.0
helm-operator	flux     	4       	2020-09-22 19:48:30.745345631 +0000 UTC	deployed	helm-operator-1.2.0	1.2.0
```

```
[tmcneely@local admin-tools] (⎈ |sea1sbx:flux)$ helm get values helm-operator
USER-SUPPLIED VALUES:
chartsSyncInterval: 2m
git:
  pollInterval: 2m
  ssh:
    known_hosts: |
      # bitbucket.company.com:22 SSH-2.0-SSHD-UNKNOWN
      # bitbucket.company.com:22 SSH-2.0-SSHD-UNKNOWN
      bitbucket.company.com ssh-rsa AAAA(CENSORED)67IHZ
      # bitbucket.company.com:22 SSH-2.0-SSHD-UNKNOWN
    secretName: flux-ssh
helm:
  versions: v3
logReleaseDiffs: true
```

... so, I stand corrected, our sync interval is 2 mins :)


~tommy

**Comment by HaveFun83** [comment]
same here running helm-operator v1.2.0  `/root/.cache/helm/repository` is never cleaned up and fill the whole /var partition.

**Comment by HaveFun83** [comment]
as workaround we created a sizelimit for the emptydir within the deployment
```
      - emptyDir:
          sizeLimit: 1Gi
        name: repositories-cache
```

**Comment by zzvara** [comment]
We are encountering full disks every month.

**Comment by TJM** [comment]
What is the validation process to get a fix for this going? At a minimum, the size limit, maybe some sort of cache cleanup sidecar? or a command line option to allow it to actually *use* the cache and not download the entire (sometimes 10MB) index.yml every time?

**Comment by TJM** [comment]
To clarify what @HaveFun83 said... I added the following to the `values:` section for the helmrelease (if you aren't managing helm-operator with a HelmRelease, you may have to unindent by 4 spaces)

```
    extraVolumes:
      - name: helm-cache
        emptyDir:
          sizeLimit: 2G
    extraVolumeMounts:
      - name: helm-cache
        mountPath: /root/.cache
```

The limit does not appear in `df -h`, but it is enforced...

```
  Normal   Started              23m   kubelet            Started container flux-helm-operator
  Warning  Evicted              45s   kubelet            Usage of EmptyDir volume "helm-cache" exceeds the limit "2G".
  Normal   Killing              45s   kubelet            Stopping container flux-helm-operator
  Warning  ExceededGracePeriod  35s   kubelet            Container runtime did not kill the pod within specified grace period.
```

NOTE: I artificially caused the eviction using `dd`.
