### ISSUE TITLE
insecure_skip_tls_verify isn't respected in a given repositories.yaml

### ISSUE THREAD

**Issue by ghost** [fluxcd/helm-operator#557]
**Describe the bug**

Given the following `repositories.yaml`, the option `insecure_skip_tls_verify: true` is not respected when helm-operator fetches the charts from the repository.

```yaml
apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: true
  keyFile: ""
  name: myawesomereponame
  password: myawesomepassword
  url: https://myawesomehelmrepo.com
  username: myawesomeuser
```

**To Reproduce**

Create a HelmRelease that fetches a chart from a repository with a certificate that's signed by an unknown authority. ( commonly a company internal CA ).

**Expected behavior**

I expect `insecure_skip_tls_verify` to be a respected option when fetching the chart.

**Logs**

```log
ts=2020-10-24T13:03:02.506603686Z caller=release.go:85 component=release release=myawesomerelease targetNamespace=myawesomenamespace resource=myawesomenamespace:helmrelease/myawesomerelease helmVersion=v3 error="failed to prepare chart for release: chart unavailable: looks like \"https://myawesomehelmrepo.com/\" is not a valid chart repository or cannot be reached: Get \"https://myawesomehelmrepo.com/index.yaml\": x509: certificate signed by unknown authority"
```

**Additional context**

- Helm Operator version: 1.2.0
- Kubernetes version: v1.17.3
- Git provider:
- Helm repository provider:
