### ISSUE TITLE
helm-operator continually installs the same helm chart 

### ISSUE THREAD

**Issue by davidg-sainsbury** [fluxcd/helm-operator#563]
**Describe the bug**

We are installing Kiali-server via flux helm-operator.  There are no changes to the kiali manifests or chart but helm-operator detects a difference and installs the kiali helm chart over and over again as per the sync value.  This has resulted in thousands of helm deployments for the same helm chart. 

**To Reproduce**

flux manifest

```
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kiali
spec:
  releaseName: kiali
  chart:
    repository: https://kiali.org/helm-charts
    name: kiali-server
    version: 1.25.0
  values:
    auth:
      strategy: token
    deployment:
      ingress_enabled: false
      replicas: 3
      view_only_mode: true
```

```
kubectl describe helmrelease kiali -n istio-system
Name:         kiali
Namespace:    istio-system
Labels:       fluxcd.io/sync-gc-mark=sha256.fUmtmNyY60STNGvbi4AWtweJisQ9HdZTDGPCfgmeZ4s
Annotations:  fluxcd.io/sync-checksum: 6537cb30aa7cfd600d178afc0863cc9eeff749ae
              kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"helm.fluxcd.io/v1","kind":"HelmRelease","metadata":{"annotations":{"fluxcd.io/sync-checksum":"6537cb30aa7cfd600d178afc0863c...
API Version:  helm.fluxcd.io/v1
Kind:         HelmRelease
Metadata:
  Creation Timestamp:  2020-11-05T12:00:34Z
  Generation:          1
  Resource Version:    61154944
  Self Link:           /apis/helm.fluxcd.io/v1/namespaces/istio-system/helmreleases/kiali
  UID:                 4feb3755-f957-4e60-ac74-7c05705f5e6a
Spec:
  Chart:
    Name:        kiali-server
    Repository:  https://kiali.org/helm-charts
    Version:     1.25.0
  Release Name:  kiali
  Values:
    Auth:
      Strategy:  token
    Deployment:
      ingress_enabled:  false
      node_selector:
        Node Type:     mgmt
      Replicas:        3
      view_only_mode:  true
Status:
  Conditions:
    Last Transition Time:   2020-11-05T12:00:34Z
    Last Update Time:       2020-11-05T12:00:34Z
    Message:                Chart fetch was successful for Helm release 'kiali' in 'istio-system'.
    Reason:                 ChartFetched
    Status:                 True
    Type:                   ChartFetched
    Last Transition Time:   2020-11-06T10:18:55Z
    Last Update Time:       2020-11-06T10:18:55Z
    Message:                Installation or upgrade succeeded for Helm release 'kiali' in 'istio-system'.
    Reason:                 Deployed
    Status:                 True
    Type:                   Deployed
    Last Transition Time:   2020-11-05T12:10:42Z
    Last Update Time:       2020-11-06T10:18:56Z
    Message:                Release was successful for Helm release 'kiali' in 'istio-system'.
    Reason:                 Succeeded
    Status:                 True
    Type:                   Released
  Last Attempted Revision:  1.25.0
  Observed Generation:      1
  Phase:                    Succeeded
  Release Name:             kiali
  Release Status:           deployed
  Revision:                 1.25.0
Events:
  Type    Reason         Age                   From           Message
  ----    ------         ----                  ----           -------
  Normal  ReleaseSynced  3m5s (x432 over 21h)  helm-operator  managed release 'kiali' in namespace 'istio-system' synchronized
```

**Logs**

```
{"caller":"helm.go:69","component":"helm","info":"performing update for kiali","release":"kiali","targetNamespace":"istio-system","ts":"2020-11-06T10:00:55.550113844Z","version":"v3"}
{"caller":"helm.go:69","component":"helm","info":"dry run for kiali","release":"kiali","targetNamespace":"istio-system","ts":"2020-11-06T10:00:55.656900076Z","version":"v3"}
{"caller":"release.go:303","component":"release","helmVersion":"v3","info":"difference detected during release comparison","phase":"dry-run-compare","release":"kiali","resource":"istio-system:helmrelease/kiali","targetNamespace":"istio-system","ts":"2020-11-06T10:00:56.060641089Z"}
{"action":"upgrade","caller":"release.go:353","component":"release","helmVersion":"v3","info":"running upgrade","release":"kiali","resource":"istio-system:helmrelease/kiali","targetNamespace":"istio-system","ts":"2020-11-06T10:00:56.060698897Z"}
{"caller":"helm.go:69","component":"helm","info":"preparing upgrade for kiali","release":"kiali","targetNamespace":"istio-system","ts":"2020-11-06T10:00:56.089728784Z","version":"v3"}
{"caller":"helm.go:69","component":"helm","info":"resetting values to the chart's original version","release":"kiali","targetNamespace":"istio-system","ts":"2020-11-06T10:00:56.106530037Z","version":"v3"}
{"caller":"helm.go:69","component":"helm","info":"performing update for kiali","release":"kiali","targetNamespace":"istio-system","ts":"2020-11-06T10:00:56.896154083Z","version":"v3"}
{"caller":"helm.go:69","component":"helm","info":"creating upgraded release for kiali","release":"kiali","targetNamespace":"istio-system","ts":"2020-11-06T10:00:57.091720321Z","version":"v3"}
{"caller":"helm.go:69","component":"helm","info":"checking 27 resources for changes","release":"kiali","targetNamespace":"istio-system","ts":"2020-11-06T10:00:57.417725844Z","version":"v3"}
{"caller":"helm.go:69","component":"helm","info":"Looks like there are no changes for ServiceAccount \"kiali\"","release":"kiali","targetNamespace":"istio-system","ts":"2020-11-06T10:00:57.430886037Z","version":"v3"}
{"caller":"helm.go:69","component":"helm","info":"Looks like there are no changes for ClusterRole \"kiali-viewer\"","release":"kiali","targetNamespace":"istio-system","ts":"2020-11-06T10:00:57.47432003Z","version":"v3"}
...
```
Detailed log snippet from helm-operator (after setting logReleaseDiff in helm-operator values.yaml)
```
="difference detected during release comparison" diff="  &helm.Chart{\n  \tName:       \"kiali-server\",\n  \tVersion:    \"1.26.0\",\n  \tAppVersion: \"v1.26.0\",\n  
\t\t\"istio_namespace\": string(\"\"),\n  \t\t\"kiali_route_url\": string(\"\"),\n- \t\t\"login_token\":    
 map[string]interface{}{\"signing_key\": string(\"WlQ0a4dPfradWB8Q123\")},\n+ \t\t\"login_token\":     
 map[string]interface{}{\"signing_key\": string(\"xdqXEd33OKqGAGg4xx\")}
map[string]interface{}{\"signing_key\": string(\"9goVqx8mdvIXDF6B234\")},\n+ \t\t\"login_token\":     
 map[string]interface{}{\"signing_key\": string(\"O0QcjsTsgkXngay7111\")}
```

As shown in the log snippet, it appears that the login authentication method when using a Service Account creates a new signing key for the login_token.  Is there any way we can get helm-operator to ignore this difference? 

**Additional context**

helm-operator chart: 1.2.0 	version: 1.2.0
kubernetes: EKS 1.16
kiali-server chart: 1.25.0	version: 1.25.0

**Comment by tomgoren** [comment]
We encountered the same issue when specifying a chart repository, but not when using `git` as the chart source.

**Comment by masterkain** [comment]
I have the same problem with `ingress-nginx` chart , `drone-runner-kube` and `cert-manager`
hundreds of revisions are being created at the moment.

```
spec:
  releaseName: ingress-nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx
    name: ingress-nginx
    version: 3.15.2
```

```
spec:
  releaseName: drone-runner-kube
  chart:
    git: https://github.com/drone/charts.git
    ref: master
    path: charts/drone-runner-kube
```

```
spec:
  releaseName: cert-manager
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v1.1.0
```

it is also happening on a custom chart, going to enable log diff
