### ISSUE TITLE
Provide option to not automatically uninstall on failed install.

### ISSUE THREAD

**Issue by anandpartha** [fluxcd/helm-operator#568]
When a helmRelease fails to install successfully, helmOperator currently automatically deletes. That may not be desirable and may want to keep the helmChart for inspection before deleting it.  Providing an option in the HelmRelease to configure this behavior will be great.

**Comment by stefanprodan** [comment]
Such an option exists in Flux2 helm-controller, docs here https://toolkit.fluxcd.io/components/helm/helmreleases/#configuring-failure-remediation

TLDR:
```yaml
apiVersion: helm.fluxcd.io/v2beta1
kind: HelmRelease
spec:
  install:
      remediateLastFailure: false
```
