### ISSUE TITLE
Helm chart mangles backslashes in passwords

### ISSUE THREAD

**Issue by dimbleby** [fluxcd/helm-operator#629]
**Describe the bug**

The helm operator's helm chart adds double quotes around password strings - which gives them a different meaning than was intended.

**To Reproduce**

values.yaml:
```yaml
helm:
  versions: v3
configureRepositories:
  enable: true
  repositories:
    - name: fluxcd
      password: this-\-is-a-literal-backslash
      url: https://charts.fluxcd.io
      username: dimbleby
```
Then `helm template helm-operator fluxcd/helm-operator -f values.yaml`.

Extract the data in the resulting `flux-helm-repositories` secret and base64-decode it, the result is this:

```yaml
generated: 0001-01-01T00:00:00Z
repositories:
- name: fluxcd
  url: https://charts.fluxcd.io
  cache: /var/fluxd/helm/repository/cache/fluxcd-index.yaml
  caFile: ""
  certFile: ""
  keyFile: ""
  password: "this-\-is-a-literal-backslash"
  username: "dimbleby"
```

The problem is that in YAML, backslashes in a double-quoted string act as an escape character.  So although I passed in a password with a literal backslash in it, I have ended up with a password that contains an invalid escape sequence.

Equivalently I could have set `password: "this-\\-is-a-literal-backslash"` in `values.yaml`: this results in the exact same faulty `repositories.yaml`.

**Expected behavior**

The password that is provided in `values.yaml` should be passed through unaltered.

**Logs**

**Additional context**

Possibly the solution is as simple as: don't add the double quotes in the template [here](https://github.com/fluxcd/helm-operator/blob/59d4046e7b0e314bfb828d500a5f4e35e874ee71/chart/helm-operator/templates/_helpers.tpl#L70)?  

Edit: actually it looks as though the expected thing to do is to pass the string through `quote` - per https://helm.sh/docs/chart_template_guide/functions_and_pipelines/.

Presumably the same issue is true for other fields here, but the password is where I hit it and where it seems most likely to be hit.
