### ISSUE TITLE
Helm Operator Warns About Failure To Annotate Resources

### ISSUE THREAD

**Issue by jeff-minard-ck** [fluxcd/helm-operator#634]
Helm Operator reporting error applying annotations:

```
failed to annotate release resources: error: arguments in resource/name form must have a single resource and name
```

This appears to be a notification [from kubectl](https://gitlab.cncf.ci/kubernetes/kubernetes/blob/874fca652d1a6ad3ff2807f331338042769f900a/pkg/kubectl/resource/builder.go#L427-440) in which something like this was done:

```
kubectl annotate --overwrite --namespace kube-system service/heapster-telegraf /heapster-telegraf test=anno
```

Note the missing `<type>` in front of the second item.

This code is run from [the annotator](https://github.com/fluxcd/helm-operator/blob/abb79a3becb5dca95faa7844b58c32d27ae04c56/pkg/release/annotator.go#L61-L88) where it compiles the list from [namespacedResourceMap](https://github.com/fluxcd/helm-operator/blob/abb79a3becb5dca95faa7844b58c32d27ae04c56/pkg/release/annotator.go#L123-L134).

My guess is that something in the code `res := obj.GetKind() + "/" + obj.GetName()` is returning an empty string causing the above error from kubectl.

**To Reproduce**

I don't have a HelmRelease or chart I can share for this error.

**Expected behavior**

Annotations are applied to all valid resources and invalid ones are warnings.

**Additional context**

- Helm Operator version: 1.4.0
- Kubernetes version: 1.18

---

_(Yes, v2, I hear ya -- we're eagerly awaiting [a solution option](https://github.com/fluxcd/helm-controller/pull/208) for the [no cross namespace valuesFrom](https://fluxcd.io/docs/migration/helm-operator-migration/#values-from-configmap-and-secret-resources-in-other-namespaces-are-no-longer-supported) as we're one of those groups that leans very heavily on that v1 feature.)_

**Comment by jeff-minard-ck** [comment]
I can provide a slightly sanitized version of the helm manifest from the HelmRelease which issues one of these warnings (several do).

<details>
<summary>manifest.yaml</summary>

```yaml
---
# Source: ourchart/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: ourchart
    chart: "ourchart-1.0.0"
    heritage: Helm
    release: kube-system-heapster-telegraf
  name: "kube-system-heapster-telegraf-heapster-telegraf-0-0-1-156-8d91b"
---
# Source: ourchart/templates/app-specific/infsvcs_k8s-heapster.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: ourchart
    chart: "ourchart-1.0.0"
    heritage: Helm
    release: kube-system-heapster-telegraf
  name: "kube-system-heapster-telegraf-heapster-telegraf-0-0-1-156-8d91b"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "system:heapster"
subjects:
- kind: ServiceAccount
  name: "kube-system-heapster-telegraf-heapster-telegraf-0-0-1-156-8d91b"
  namespace: kube-system

#
---
# Source: ourchart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "heapster-telegraf"
  labels:
    app: "kube-system-heapster-telegraf-ourchart"
    created_by: "ourchart-chart"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8082
    protocol: TCP
  selector:
    app: "kube-system-heapster-telegraf-ourchart"
    deployment: ""
---
# Source: ourchart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "heapster-telegraf"
  labels:
    app: "kube-system-heapster-telegraf-ourchart"
    created_by: "ourchart-chart"
  annotations:
    creditkarma.com/all: "true"
    sidecar-injector.creditkarma.com/traffic-proxy: "disabled"
spec:
  selector:
    matchLabels:
      app: "kube-system-heapster-telegraf-ourchart"
      created_by: "ourchart-chart"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "0%"
      maxUnavailable: "5%"
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      name: "heapster-telegraf"
      labels:
        app: "kube-system-heapster-telegraf-ourchart"
        created_by: "ourchart"
      annotations:
        ours/all: "true"
        sidecarthing: "disabled"
    spec:
      dnsPolicy: ClusterFirst
      hostNetwork: false
      serviceAccountName: "kube-system-heapster-telegraf-heapster-telegraf-0-0-1-156-8d91b"
      containers:
      - name: ourchart
        image: "image/path/k8s-heapster:0.0.1-1564776195-2aba5fa1d4a8"
        imagePullPolicy: "IfNotPresent"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
          - /heapster
          - --source=kubernetes.summary_api:?host_id_annotation=container.googleapis.com/instance_id
          - --sink=influxdb:http://$(NODE_IP):2200?$(INFLUXDB_OPTIONS)
        ports:
        - name: "http"
          containerPort: 8082
          protocol: TCP
        resources:
          limits:
            cpu: 10000m
            memory: 1024Mi
          requests:
            cpu: 1000m
            memory: 1024Mi
```

</details>
