### ISSUE TITLE
by default how many retries does helm attempt

### ISSUE THREAD

**Issue by aizada92** [fluxcd/helm-operator#653]
Hello , I have a question about Helm ,by default how many retries does helm attempt ? i was setting   up notification for helm failures in fluxv2. 
```
install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure:  true  
```

I add this lines but how I can check if it is working ? 

Thankyou
