### ISSUE TITLE
using  secretKeyRef in HelmRelease dosent working

### ISSUE THREAD

**Issue by guyalo** [fluxcd/helm-operator#665]
Hi, trying to use secretKeyRef in the HelmRelease values section but doesn't evaluate the secretKeyRef but uses the literal object.

flux2 version: flux version 0.31.1
environment:: GKE

 yaml:
 
```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq
spec:
  releaseName: rabbitmq
  chart:
    spec:
      chart: rabbitmq
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    service:
      type: LoadBalancer
    auth:
      password:
        valueFrom:
          secretKeyRef:
            name: rabbitmq-password
            key: value
```
For checking the secret that created by the rabbitmq chart running :
> kubectl get secret rabbitmq -n stage -o go-template='{{range $k,$v := .data}}{{printf "%s: " $k}}{{if not $v}}{{$v}}{{else}}{{$v | base64decode}}{{end}}{{"\n"}}{{end}}'

result is:
> rabbitmq-password: map[valueFrom:map[secretKeyRef:map[key:value name:rabbitmq-password]]]

the secret were not evaluated
