### ISSUE TITLE
'no repository definition' error, but repos have been configured

### ISSUE THREAD

**Issue by brew** [fluxcd/helm-operator#68]
I'm trying to use the Helm Operator to release a Helm Chart (v3 syntax) that defines a dependency. I get a Helm error about 'no repository definition', but I think I've added the chart repo correctly. If I remove the dependency section, the chart installs.

Perhaps related to #18.

When I deployed the helm operator (via a git checkout d42759d03d341f052a612568bbc3708a04670871), I added a couple of chart repos:

```sh
helm upgrade -i helm-operator ./chart/helm-operator --wait \
--namespace fluxcd \
--set git.ssh.secretName=flux-git-deploy \
--set git.pollInterval=1m \
--set chartsSyncInterval=1m \
--set configureRepositories.enable=true \
--set configureRepositories.repositories\[0\].name=stable \
--set configureRepositories.repositories\[0\].url=https://kubernetes-charts.storage.googleapis.com \
--set configureRepositories.repositories\[1\].name=bitnami \
--set configureRepositories.repositories\[1\].url=https://charts.bitnami.com/bitnami \
--set extraEnvs\[0\].name=HELM_VERSION \
--set extraEnvs\[0\].value=v3 \
--set image.repository=docker.io/fluxcd/helm-operator \
--set image.tag=helm-v3-9908b258
```

I checked that the repositories are in the `secret/flux-helm-repositories` secret:

```sh
kubectl get -n fluxcd secret flux-helm-repositories --output="jsonpath={.data.repositories\.yaml}" | base64 --decode

apiVersion: v1
generated: 0001-01-01T00:00:00Z
repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
  cache: /var/fluxd/helm/repository/cache/stable-index.yaml
  caFile: ""
  certFile: ""
  keyFile: ""
  password: ""
  username: ""
- name: bitnami
  url: https://charts.bitnami.com/bitnami
  cache: /var/fluxd/helm/repository/cache/bitnami-index.yaml
  caFile: ""
  certFile: ""
  keyFile: ""
  password: ""
  username: ""% 
```

My Helm chart defines a dependency in `Chart.yaml`:

```yaml
apiVersion: v2
name: mygreatapp
description: A Helm chart for mygreatapp
type: application
version: 0.1.0
appVersion: 1.0.0
dependencies:
  - name: mongodb
    version: 7.3.0
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
```

My HelmRelease manifest looks like:

```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mygreatapp-stage
  namespace: fluxcd
  annotations:
    fluxcd.io/ignore: "false"
spec:
  releaseName: mygreatapp-stage
  targetNamespace: stage
  chart:
    git: git@github.com:myorg/infrastructure
    path: charts/mygreatapp
```

I get a Helm error reported by the helm-operator:

```sh
ts=2019-10-10T09:13:19.2217093Z caller=operator.go:322 component=operator info="enqueuing release" resource=fluxcd:helmrelease/mygreatapp-stage
ts=2019-10-10T09:13:19.2807463Z caller=chartsync.go:555 component=chartsync release=mygreatapp-stage targetNamespace=stage resource=fluxcd:helmrelease/mygreatapp-stage warning="failed to update chart dependencies" err="no repository definition for https://charts.bitnami.com/bitnami. Please add them via 'helm repo add'"
```

And the HelmRelease message is similar:

```sh
NAME                                            RELEASE   STATUS   MESSAGE                                                                                                AGE
helmrelease.helm.fluxcd.io/mygreatapp-stage                        no repository definition for https://charts.bitnami.com/bitnami. Please add them via 'helm repo add'   35m
```

**Comment by stefanprodan** [comment]
I see a `%` in `  username: ""% ` also what's with `\` in `configureRepositories.repositories\[1\].url=https://charts.bitnami.com/bitnami`

**Comment by stefanprodan** [comment]
Pleaser use a bash shell and it will work ok

**Comment by brew** [comment]
I tried using bash and also by passing a values file (instead of using `--set`) to the `helm install` command. Same result. The `repositories.yaml` file is mounted into the helm operator pod and looks okay. I notice `helm version` isn't version 3 in the helm operator pod.

```
kubectl exec -it helm-operator-7474fd48f5-kwv4f sh

/home/flux # cd /var/fluxd/helm/repository/

/var/fluxd/helm/repository # cat repositories.yaml
apiVersion: v1
generated: 0001-01-01T00:00:00Z
repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
  cache: /var/fluxd/helm/repository/cache/stable-index.yaml
  caFile: ""
  certFile: ""
  keyFile: ""
  password: ""
  username: ""
- name: bitnami
  url: https://charts.bitnami.com/bitnami
  cache: /var/fluxd/helm/repository/cache/bitnami-index.yaml
  caFile: ""
  certFile: ""
  keyFile: ""
  password: ""
  username: ""

/var/fluxd/helm/repository # helm version
Client: &version.Version{SemVer:"v2.13.0", GitCommit:"79d07943b03aea2b76c12644b4b54733bc5958d6", GitTreeState:"clean"}
Error: could not find tiller
```

**Comment by stefanprodan** [comment]
Helm Operator doesn't use the binary, the v2 CLI is there for debugging purposes.

To fix the dependency you need to use the same name as in Chart.yaml, there is `https://charts.bitnami.com/bitnami` but you've added it as `bitnami`.

**Comment by brew** [comment]
If I leave the `repository` value in Chart.yaml as the url, but change the value in the helm operator to use the url for both the `url` and the `name` (I think that's what you're suggesting, correct me if I'm wrong!):

```yaml
configureRepositories:
  enable: true
  repositories:
    - name: https://charts.bitnami.com/bitnami
      url: https://charts.bitnami.com/bitnami
```

I get a similar error:

> ts=2019-10-10T11:49:26.3788584Z caller=chartsync.go:555 component=chartsync release=mygreatapp-stage targetNamespace=stage resource=fluxcd:helmrelease/mygreatapp-stage warning="failed to update chart dependencies" err="no repository definition for https://charts.bitnami.com/bitnami. Please add them via 'helm repo add'"

Instead, if I change the repo name in Chart.yaml to `bitnami` I get an different error: 

> ts=2019-10-10T11:36:14.4865453Z caller=chartsync.go:555 component=chartsync release=mygreatapp-stage targetNamespace=stage resource=fluxcd:helmrelease/mygreatapp-stage warning="failed to update chart dependencies" err="no repository definition for bitnami. Please add them via 'helm repo add'\nNote that repositories must be URLs or aliases. For example, to refer to the \"example\"\nrepository, use \"https://charts.example.com/\" or \"@example\" instead of\n\"example\". Don't forget to add the repo, too ('helm repo add')."
