### ISSUE TITLE
Helm release revision created every minute if secretKeyRef used

### ISSUE THREAD

**Issue by brew** [fluxcd/helm-operator#69]
If a `secretKeyRef` is defined in the HelmRelease manifest, the helm-operator creates a new helm release every minute.

#### with `secretKeyRef`

With the following HelmRelease file pushed to my repo:

```yaml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: stage
  annotations:
    fluxcd.io/ignore: "false"
spec:
  releaseName: podinfo-stage
  targetNamespace: stage
  chart:
    git: git@github.com:myorg/infrastructure
    ref: 14/gitops
    path: k8s/charts/podinfo
  valuesFrom:
  - configMapKeyRef:
      name: podinfo-stage-values
      key: stage.values.yaml
  - secretKeyRef:
      name: podinfo-stage-secrets
      key: stage.secrets.yaml      
```

The helmrelease is created, and podinfo workloads created as expected, including a helm release secret `secret/podinfo-stage.v1`. After a minute another helm release secret is created, `secret/podinfo-stage.v2`. This carries on every minute.

```sh
NAME                           TYPE                                  DATA   AGE
secret/default-token-whxz6     kubernetes.io/service-account-token   3      27h
secret/podinfo-stage-secrets   Opaque                                1      19m
secret/podinfo-stage.v1        helm.sh/release                       1      2m23s
secret/podinfo-stage.v2        helm.sh/release                       1      91s
secret/podinfo-stage.v3        helm.sh/release                       1      30s
```

#### without `secretKeyRef`

Clean up the release by setting `fluxcd.io/ignore: "true"`, commit and push, then use `kubectl` to delete the helmrelease.

Edit the HelmRelease file to remove the `secretKeyRef` section (reset `fluxcd.io/ignore: "false"`), and commit and push it.

This creates the helmrelease again, and the podinfo workloads. This time, only one helm release secret is created, and no other releases are created after a minute.

**Additional context**
Add any other context about the problem here, e.g 
- Helm operator version: chart from commit 8f5bbeb9ec47569280df94cb0b3470611f826527 with the following values:

```yaml
git:
  ssh:
    secretName: flux-git-deploy
  pollInterval: 1m

chartsSyncInterval: 1m

configureRepositories:
  enable: true
  repositories:
    - name: https://charts.bitnami.com/bitnami
      url: https://charts.bitnami.com/bitnami
    - name: https://kubernetes-charts.storage.googleapis.com/
      url: https://kubernetes-charts.storage.googleapis.com/

extraEnvs:
  - name: HELM_VERSION
    value: v3

image:
  repository: docker.io/fluxcd/helm-operator-prerelease
  tag: helm-v3-71bc9d62
```
